/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guiFrame;

/**
 *
 * @author juandapp
 */
public class JPAbonado extends javax.swing.JPanel {

    /**
     * Creates new form JPAbonado
     */
    public JPAbonado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
