/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author JUANPAULO
 */
public class JPEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form JPEmpresa
     */
    public JPEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jBLimpiar1 = new javax.swing.JButton();
        jBCrear1 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jTFNombre1 = new javax.swing.JTextField();
        jCBCod_plan1 = new javax.swing.JComboBox();
        jLabel51 = new javax.swing.JLabel();
        jTFTelefono1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jTFDireccion1 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jTFNombre2 = new javax.swing.JTextField();
        jCBCod_plan2 = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        jTFTelefono2 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTFDireccion2 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jBConsultar2 = new javax.swing.JButton();
        jBLimpiar2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jBModificar3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jTFNombre3 = new javax.swing.JTextField();
        jCBCod_plan3 = new javax.swing.JComboBox();
        jLabel57 = new javax.swing.JLabel();
        jTFTelefono3 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jTFDireccion3 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));
        jPanel3.setLayout(null);

        jPanel1.setLayout(null);

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar1);
        jBLimpiar1.setBounds(140, 150, 80, 23);

        jBCrear1.setText("Crear");
        jPanel1.add(jBCrear1);
        jBCrear1.setBounds(240, 150, 90, 23);

        jLabel25.setText("Nombre");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(10, 10, 80, 14);
        jPanel1.add(jTFNombre1);
        jTFNombre1.setBounds(130, 10, 200, 20);

        jCBCod_plan1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Planes Postpago" }));
        jCBCod_plan1.setName(""); // NOI18N
        jCBCod_plan1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBCod_plan1PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel1.add(jCBCod_plan1);
        jCBCod_plan1.setBounds(130, 100, 200, 20);

        jLabel51.setText("Telefono");
        jPanel1.add(jLabel51);
        jLabel51.setBounds(10, 40, 80, 14);
        jPanel1.add(jTFTelefono1);
        jTFTelefono1.setBounds(130, 40, 200, 20);

        jLabel52.setText("Plan");
        jPanel1.add(jLabel52);
        jLabel52.setBounds(10, 100, 80, 14);
        jPanel1.add(jTFDireccion1);
        jTFDireccion1.setBounds(130, 70, 200, 20);

        jLabel53.setText("Direccion");
        jPanel1.add(jLabel53);
        jLabel53.setBounds(10, 70, 80, 14);

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(null);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Telefono", "Direccion", "Plan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 440, 120);

        jLabel26.setText("Nombre");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(10, 10, 80, 14);
        jPanel2.add(jTFNombre2);
        jTFNombre2.setBounds(130, 10, 200, 20);

        jCBCod_plan2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Planes Postpago" }));
        jCBCod_plan2.setName(""); // NOI18N
        jCBCod_plan2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBCod_plan2PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel2.add(jCBCod_plan2);
        jCBCod_plan2.setBounds(130, 100, 200, 20);

        jLabel54.setText("Telefono");
        jPanel2.add(jLabel54);
        jLabel54.setBounds(10, 40, 80, 14);
        jPanel2.add(jTFTelefono2);
        jTFTelefono2.setBounds(130, 40, 200, 20);

        jLabel55.setText("Plan");
        jPanel2.add(jLabel55);
        jLabel55.setBounds(10, 100, 80, 14);
        jPanel2.add(jTFDireccion2);
        jTFDireccion2.setBounds(130, 70, 200, 20);

        jLabel56.setText("Direccion");
        jPanel2.add(jLabel56);
        jLabel56.setBounds(10, 70, 80, 14);

        jBConsultar2.setText("Consultar");
        jPanel2.add(jBConsultar2);
        jBConsultar2.setBounds(360, 20, 100, 23);

        jBLimpiar2.setText("Limpiar");
        jPanel2.add(jBLimpiar2);
        jBLimpiar2.setBounds(360, 50, 100, 23);

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel4.setLayout(null);

        jBModificar3.setText("Modificar");
        jPanel4.add(jBModificar3);
        jBModificar3.setBounds(240, 140, 90, 23);

        jLabel27.setText("Nombre");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(10, 10, 80, 14);
        jPanel4.add(jTFNombre3);
        jTFNombre3.setBounds(130, 10, 200, 20);

        jCBCod_plan3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Planes Postpago" }));
        jCBCod_plan3.setName(""); // NOI18N
        jCBCod_plan3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBCod_plan3PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel4.add(jCBCod_plan3);
        jCBCod_plan3.setBounds(130, 100, 200, 20);

        jLabel57.setText("Telefono");
        jPanel4.add(jLabel57);
        jLabel57.setBounds(10, 40, 80, 14);
        jPanel4.add(jTFTelefono3);
        jTFTelefono3.setBounds(130, 40, 200, 20);

        jLabel58.setText("Plan");
        jPanel4.add(jLabel58);
        jLabel58.setBounds(10, 100, 80, 14);
        jPanel4.add(jTFDireccion3);
        jTFDireccion3.setBounds(130, 70, 200, 20);

        jLabel59.setText("Direccion");
        jPanel4.add(jLabel59);
        jLabel59.setBounds(10, 70, 80, 14);

        jTabbedPane1.addTab("Editar", jPanel4);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 480, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCBCod_plan1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBCod_plan1PopupMenuWillBecomeVisible

    }//GEN-LAST:event_jCBCod_plan1PopupMenuWillBecomeVisible

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    private void jCBCod_plan2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBCod_plan2PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBCod_plan2PopupMenuWillBecomeVisible

    private void jCBCod_plan3PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBCod_plan3PopupMenuWillBecomeVisible
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBCod_plan3PopupMenuWillBecomeVisible

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar2;
    private javax.swing.JButton jBCrear1;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiar2;
    private javax.swing.JButton jBModificar3;
    private javax.swing.JComboBox jCBCod_plan1;
    private javax.swing.JComboBox jCBCod_plan2;
    private javax.swing.JComboBox jCBCod_plan3;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFDireccion1;
    private javax.swing.JTextField jTFDireccion2;
    private javax.swing.JTextField jTFDireccion3;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFNombre2;
    private javax.swing.JTextField jTFNombre3;
    private javax.swing.JTextField jTFTelefono1;
    private javax.swing.JTextField jTFTelefono2;
    private javax.swing.JTextField jTFTelefono3;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
