/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author JUANPAULO
 */
public class JPEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form JPEmpleado
     */
    public JPEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jTFCodigo1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTFNombre1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jCBGenero1 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jCBEstadoCivil1 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jTFFechaNacimiento1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTFFechaIngreso1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jCBTipoContrato1 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jCBCargo1 = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jCBSucursal1 = new javax.swing.JComboBox();
        jBLimpiar1 = new javax.swing.JButton();
        jBCrear1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTFCodigo2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTFNombre2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTFFechaIngreso2 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jTFFechaNacimiento2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jCBGenero2 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        jCBEstadoCivil2 = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jCBCargo2 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jCBTipoContrato2 = new javax.swing.JComboBox();
        jLabel41 = new javax.swing.JLabel();
        jCBSucursal2 = new javax.swing.JComboBox();
        jBLimpiar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jTFCodigo3 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTFNombre3 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jCBGenero3 = new javax.swing.JComboBox();
        jLabel45 = new javax.swing.JLabel();
        jCBEstadoCivil3 = new javax.swing.JComboBox();
        jLabel46 = new javax.swing.JLabel();
        jTFFechaNacimiento3 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTFFechaIngreso3 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jCBTipoContrato3 = new javax.swing.JComboBox();
        jLabel49 = new javax.swing.JLabel();
        jCBCargo3 = new javax.swing.JComboBox();
        jLabel50 = new javax.swing.JLabel();
        jCBSucursal3 = new javax.swing.JComboBox();
        jBCrear2 = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleado"));
        jPanel3.setLayout(null);

        jPanel1.setLayout(null);

        jLabel24.setText("Id");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(10, 10, 12, 18);
        jPanel1.add(jTFCodigo1);
        jTFCodigo1.setBounds(130, 10, 100, 28);

        jLabel25.setText("Nombre");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(10, 40, 80, 18);
        jPanel1.add(jTFNombre1);
        jTFNombre1.setBounds(130, 40, 140, 28);

        jLabel26.setText("Genero");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 70, 70, 18);

        jCBGenero1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero1.setName(""); // NOI18N
        jPanel1.add(jCBGenero1);
        jCBGenero1.setBounds(130, 70, 140, 28);

        jLabel27.setText("Estado Civil");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(10, 100, 100, 18);

        jCBEstadoCivil1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Casado", "Soltero", "Viudo", "Divorsiado", "Union Libre" }));
        jCBEstadoCivil1.setName(""); // NOI18N
        jCBEstadoCivil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEstadoCivil1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCBEstadoCivil1);
        jCBEstadoCivil1.setBounds(130, 100, 140, 28);

        jLabel28.setText("F. de Nacimiento");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(10, 130, 130, 18);
        jPanel1.add(jTFFechaNacimiento1);
        jTFFechaNacimiento1.setBounds(130, 130, 140, 28);

        jLabel29.setText("F. de Ingreso");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(10, 160, 110, 20);
        jPanel1.add(jTFFechaIngreso1);
        jTFFechaIngreso1.setBounds(130, 160, 140, 28);

        jLabel30.setText("Tipo de Contrato");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(10, 190, 130, 20);

        jCBTipoContrato1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Casado", "Soltero", "Viudo", "Divorsiado" }));
        jCBTipoContrato1.setName(""); // NOI18N
        jPanel1.add(jCBTipoContrato1);
        jCBTipoContrato1.setBounds(130, 190, 140, 28);

        jLabel31.setText("Cargo");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(10, 220, 60, 20);

        jCBCargo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Vendedor", "Gerente" }));
        jCBCargo1.setName(""); // NOI18N
        jPanel1.add(jCBCargo1);
        jCBCargo1.setBounds(130, 220, 140, 28);

        jLabel32.setText("Sucursal");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(10, 250, 80, 20);

        jCBSucursal1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Sucursales" }));
        jCBSucursal1.setName(""); // NOI18N
        jPanel1.add(jCBSucursal1);
        jCBSucursal1.setBounds(130, 250, 140, 28);

        jBLimpiar1.setText("Limpiar");
        jPanel1.add(jBLimpiar1);
        jBLimpiar1.setBounds(130, 280, 80, 30);

        jBCrear1.setText("Crear");
        jBCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrear1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBCrear1);
        jBCrear1.setBounds(220, 280, 90, 30);

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel2.setLayout(null);
        jPanel2.add(jTFCodigo2);
        jTFCodigo2.setBounds(140, 10, 100, 28);

        jLabel33.setText("Id");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(10, 10, 12, 18);

        jLabel34.setText("Nombre");
        jPanel2.add(jLabel34);
        jLabel34.setBounds(10, 40, 80, 18);
        jPanel2.add(jTFNombre2);
        jTFNombre2.setBounds(140, 40, 140, 28);

        jLabel38.setText("F. de Ingreso");
        jPanel2.add(jLabel38);
        jLabel38.setBounds(10, 70, 110, 20);
        jPanel2.add(jTFFechaIngreso2);
        jTFFechaIngreso2.setBounds(140, 70, 140, 28);

        jLabel37.setText("F. de Nacimiento");
        jPanel2.add(jLabel37);
        jLabel37.setBounds(10, 100, 115, 18);
        jPanel2.add(jTFFechaNacimiento2);
        jTFFechaNacimiento2.setBounds(140, 100, 140, 28);

        jLabel35.setText("Genero");
        jPanel2.add(jLabel35);
        jLabel35.setBounds(310, 10, 70, 18);

        jCBGenero2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero2.setName(""); // NOI18N
        jPanel2.add(jCBGenero2);
        jCBGenero2.setBounds(390, 10, 119, 28);

        jLabel36.setText("Estado Civil");
        jPanel2.add(jLabel36);
        jLabel36.setBounds(310, 40, 100, 18);

        jCBEstadoCivil2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Casado", "Soltero", "Viudo", "Divorsiado", "Union Libre" }));
        jCBEstadoCivil2.setName(""); // NOI18N
        jPanel2.add(jCBEstadoCivil2);
        jCBEstadoCivil2.setBounds(390, 40, 119, 28);

        jLabel40.setText("Cargo");
        jPanel2.add(jLabel40);
        jLabel40.setBounds(310, 70, 60, 20);

        jCBCargo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Vendedor", "Gerente" }));
        jCBCargo2.setName(""); // NOI18N
        jPanel2.add(jCBCargo2);
        jCBCargo2.setBounds(390, 70, 119, 28);

        jLabel39.setText("Tipo de Contrato");
        jPanel2.add(jLabel39);
        jLabel39.setBounds(10, 130, 130, 20);

        jCBTipoContrato2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Casado", "Soltero", "Viudo", "Divorsiado" }));
        jCBTipoContrato2.setName(""); // NOI18N
        jPanel2.add(jCBTipoContrato2);
        jCBTipoContrato2.setBounds(140, 130, 140, 28);

        jLabel41.setText("Sucursal");
        jPanel2.add(jLabel41);
        jLabel41.setBounds(310, 100, 80, 20);

        jCBSucursal2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Sucursales" }));
        jCBSucursal2.setName(""); // NOI18N
        jCBSucursal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSucursal2ActionPerformed(evt);
            }
        });
        jPanel2.add(jCBSucursal2);
        jCBSucursal2.setBounds(390, 100, 119, 28);

        jBLimpiar2.setText("Limpiar");
        jBLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar2ActionPerformed(evt);
            }
        });
        jPanel2.add(jBLimpiar2);
        jBLimpiar2.setBounds(500, 140, 90, 30);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Genero", "Estado Civil", "Fecha Nacimiento", "Fehca Ingreso", "Tipo Contraro", "Cargo", "Sucursal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 210, 640, 140);

        jBConsultar1.setText("Consultar");
        jBConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsultar1);
        jBConsultar1.setBounds(310, 140, 150, 40);

        jTabbedPane1.addTab("Consultar", jPanel2);

        jPanel4.setLayout(null);

        jLabel42.setText("Id");
        jPanel4.add(jLabel42);
        jLabel42.setBounds(10, 10, 40, 18);

        jTFCodigo3.setEnabled(false);
        jPanel4.add(jTFCodigo3);
        jTFCodigo3.setBounds(140, 10, 100, 28);

        jLabel43.setText("Nombre");
        jPanel4.add(jLabel43);
        jLabel43.setBounds(10, 40, 90, 18);
        jPanel4.add(jTFNombre3);
        jTFNombre3.setBounds(140, 40, 140, 28);

        jLabel44.setText("Genero");
        jPanel4.add(jLabel44);
        jLabel44.setBounds(10, 70, 80, 18);

        jCBGenero3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Femenino", "Masculino" }));
        jCBGenero3.setName(""); // NOI18N
        jPanel4.add(jCBGenero3);
        jCBGenero3.setBounds(140, 70, 140, 28);

        jLabel45.setText("Estado Civil");
        jPanel4.add(jLabel45);
        jLabel45.setBounds(10, 100, 100, 18);

        jCBEstadoCivil3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Casado", "Soltero", "Viudo", "Divorsiado", "Union Libre" }));
        jCBEstadoCivil3.setName(""); // NOI18N
        jCBEstadoCivil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEstadoCivil3ActionPerformed(evt);
            }
        });
        jPanel4.add(jCBEstadoCivil3);
        jCBEstadoCivil3.setBounds(140, 100, 140, 28);

        jLabel46.setText("F. de Nacimiento");
        jPanel4.add(jLabel46);
        jLabel46.setBounds(10, 130, 130, 18);
        jPanel4.add(jTFFechaNacimiento3);
        jTFFechaNacimiento3.setBounds(140, 130, 140, 28);

        jLabel47.setText("F. de Ingreso");
        jPanel4.add(jLabel47);
        jLabel47.setBounds(10, 160, 110, 20);
        jPanel4.add(jTFFechaIngreso3);
        jTFFechaIngreso3.setBounds(140, 160, 140, 28);

        jLabel48.setText("Tipo de Contrato");
        jPanel4.add(jLabel48);
        jLabel48.setBounds(10, 190, 130, 20);

        jCBTipoContrato3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Casado", "Soltero", "Viudo", "Divorsiado" }));
        jCBTipoContrato3.setName(""); // NOI18N
        jPanel4.add(jCBTipoContrato3);
        jCBTipoContrato3.setBounds(140, 190, 140, 28);

        jLabel49.setText("Cargo");
        jPanel4.add(jLabel49);
        jLabel49.setBounds(10, 220, 90, 20);

        jCBCargo3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Vendedor", "Gerente" }));
        jCBCargo3.setName(""); // NOI18N
        jPanel4.add(jCBCargo3);
        jCBCargo3.setBounds(140, 220, 140, 28);

        jLabel50.setText("Sucursal");
        jPanel4.add(jLabel50);
        jLabel50.setBounds(10, 250, 90, 20);

        jCBSucursal3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar", "Sucursales" }));
        jCBSucursal3.setName(""); // NOI18N
        jPanel4.add(jCBSucursal3);
        jCBSucursal3.setBounds(140, 250, 140, 28);

        jBCrear2.setText("Crear");
        jBCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrear2ActionPerformed(evt);
            }
        });
        jPanel4.add(jBCrear2);
        jBCrear2.setBounds(220, 280, 90, 30);

        jTabbedPane1.addTab("Editar", jPanel4);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 670, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar2ActionPerformed

   }//GEN-LAST:event_jBLimpiar2ActionPerformed

    private void jCBSucursal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSucursal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSucursal2ActionPerformed

    private void jBCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrear1ActionPerformed

   }//GEN-LAST:event_jBCrear1ActionPerformed

    private void jCBEstadoCivil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEstadoCivil1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEstadoCivil1ActionPerformed

    private void jCBEstadoCivil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEstadoCivil3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEstadoCivil3ActionPerformed

    private void jBCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrear2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCrear2ActionPerformed

    private void jBConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBConsultar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar1;
    private javax.swing.JButton jBCrear1;
    private javax.swing.JButton jBCrear2;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiar2;
    private javax.swing.JComboBox jCBCargo1;
    private javax.swing.JComboBox jCBCargo2;
    private javax.swing.JComboBox jCBCargo3;
    private javax.swing.JComboBox jCBEstadoCivil1;
    private javax.swing.JComboBox jCBEstadoCivil2;
    private javax.swing.JComboBox jCBEstadoCivil3;
    private javax.swing.JComboBox jCBGenero1;
    private javax.swing.JComboBox jCBGenero2;
    private javax.swing.JComboBox jCBGenero3;
    private javax.swing.JComboBox jCBSucursal1;
    private javax.swing.JComboBox jCBSucursal2;
    private javax.swing.JComboBox jCBSucursal3;
    private javax.swing.JComboBox jCBTipoContrato1;
    private javax.swing.JComboBox jCBTipoContrato2;
    private javax.swing.JComboBox jCBTipoContrato3;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigo1;
    private javax.swing.JTextField jTFCodigo2;
    private javax.swing.JTextField jTFCodigo3;
    private javax.swing.JTextField jTFFechaIngreso1;
    private javax.swing.JTextField jTFFechaIngreso2;
    private javax.swing.JTextField jTFFechaIngreso3;
    private javax.swing.JTextField jTFFechaNacimiento1;
    private javax.swing.JTextField jTFFechaNacimiento2;
    private javax.swing.JTextField jTFFechaNacimiento3;
    private javax.swing.JTextField jTFNombre1;
    private javax.swing.JTextField jTFNombre2;
    private javax.swing.JTextField jTFNombre3;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
