/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author JUANPAULO
 */
public class JPEquipo extends javax.swing.JPanel {

    /**
     * Creates new form JPEquipo
     */
    public JPEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTFImei1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFModelo1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFMarca1 = new javax.swing.JTextField();
        jBLimpiar1 = new javax.swing.JButton();
        jBCrear = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTFImei2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTFModelo2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFMarca2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar2 = new javax.swing.JButton();
        jBLimpiar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTFCodigo3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFModelo3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTFMarca3 = new javax.swing.JTextField();
        jBModificar3 = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipo"));
        jPanel3.setLayout(null);

        jPanel4.setLayout(null);

        jLabel9.setText("Imei");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 10, 40, 18);
        jPanel4.add(jTFImei1);
        jTFImei1.setBounds(90, 10, 100, 28);

        jLabel6.setText("Modelo");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 40, 70, 18);
        jPanel4.add(jTFModelo1);
        jTFModelo1.setBounds(90, 40, 190, 28);

        jLabel8.setText("Marca");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 70, 60, 18);
        jPanel4.add(jTFMarca1);
        jTFMarca1.setBounds(90, 70, 190, 28);

        jBLimpiar1.setText("Limpiar");
        jPanel4.add(jBLimpiar1);
        jBLimpiar1.setBounds(90, 100, 72, 30);

        jBCrear.setText("Crear");
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });
        jPanel4.add(jBCrear);
        jBCrear.setBounds(180, 100, 70, 30);

        jTabbedPane1.addTab("Crear", jPanel4);

        jPanel1.setLayout(null);

        jLabel4.setText("Imei");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 10, 40, 18);
        jPanel1.add(jTFImei2);
        jTFImei2.setBounds(80, 10, 100, 28);

        jLabel1.setText("Modelo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 40, 60, 18);
        jPanel1.add(jTFModelo2);
        jTFModelo2.setBounds(80, 40, 160, 28);

        jLabel3.setText("Marca");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 70, 60, 18);
        jPanel1.add(jTFMarca2);
        jTFMarca2.setBounds(80, 70, 160, 28);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Imei", "Modelo", "Marca"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 390, 125);

        jBConsultar2.setText("Consultar");
        jBConsultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBConsultar2);
        jBConsultar2.setBounds(250, 10, 90, 30);

        jBLimpiar2.setText("Limpiar");
        jBLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar2);
        jBLimpiar2.setBounds(250, 40, 90, 30);

        jTabbedPane1.addTab("Consultar", jPanel1);

        jPanel2.setLayout(null);

        jLabel10.setText("Imei");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 10, 40, 18);

        jTFCodigo3.setEnabled(false);
        jPanel2.add(jTFCodigo3);
        jTFCodigo3.setBounds(80, 10, 100, 28);

        jLabel11.setText("Modelo");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 40, 60, 18);
        jPanel2.add(jTFModelo3);
        jTFModelo3.setBounds(80, 40, 190, 28);

        jLabel12.setText("Marca");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 70, 60, 18);
        jPanel2.add(jTFMarca3);
        jTFMarca3.setBounds(80, 70, 190, 28);

        jBModificar3.setText("Modificar");
        jBModificar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificar3ActionPerformed(evt);
            }
        });
        jPanel2.add(jBModificar3);
        jBModificar3.setBounds(180, 100, 90, 30);

        jTabbedPane1.addTab("Editar", jPanel2);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 410, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed

   }//GEN-LAST:event_jBCrearActionPerformed

    private void jBConsultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBConsultar2ActionPerformed

    private void jBLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar2ActionPerformed

   }//GEN-LAST:event_jBLimpiar2ActionPerformed

    private void jBModificar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBModificar3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar2;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiar2;
    private javax.swing.JButton jBModificar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigo3;
    private javax.swing.JTextField jTFImei1;
    private javax.swing.JTextField jTFImei2;
    private javax.swing.JTextField jTFMarca1;
    private javax.swing.JTextField jTFMarca2;
    private javax.swing.JTextField jTFMarca3;
    private javax.swing.JTextField jTFModelo1;
    private javax.swing.JTextField jTFModelo2;
    private javax.swing.JTextField jTFModelo3;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
