/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author JUANPAULO
 */
public class JPPlanPrepago extends javax.swing.JPanel {

    /**
     * Creates new form JPPlanPrepago
     */
    public JPPlanPrepago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTFCodigo1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFtarifa_otro_operador1 = new javax.swing.JTextField();
        jTFtarifa_msj_multimedia1 = new javax.swing.JTextField();
        jBLimpiar1 = new javax.swing.JButton();
        jBCrear1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTtarifa_msj_texto1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar2 = new javax.swing.JButton();
        jBLimpiar2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTFCodigo2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFtarifa_otro_operador2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTFtarifa_msj_multimedia2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTtarifa_msj_texto2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBModificar3 = new javax.swing.JButton();
        jTFtarifa_msj_multimedia3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTFCodigo3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTtarifa_msj_texto3 = new javax.swing.JTextField();
        jTFtarifa_otro_operador3 = new javax.swing.JTextField();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Plan Prepago"));
        jPanel3.setLayout(null);

        jPanel4.setLayout(null);

        jLabel9.setText("Codigo");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 10, 60, 14);
        jPanel4.add(jTFCodigo1);
        jTFCodigo1.setBounds(120, 10, 100, 20);

        jLabel6.setText("Tarifa otro op.");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 40, 70, 14);
        jPanel4.add(jTFtarifa_otro_operador1);
        jTFtarifa_otro_operador1.setBounds(120, 40, 110, 20);
        jPanel4.add(jTFtarifa_msj_multimedia1);
        jTFtarifa_msj_multimedia1.setBounds(120, 70, 110, 20);

        jBLimpiar1.setText("Limpiar");
        jPanel4.add(jBLimpiar1);
        jBLimpiar1.setBounds(60, 150, 72, 23);

        jBCrear1.setText("Crear");
        jPanel4.add(jBCrear1);
        jBCrear1.setBounds(150, 150, 70, 23);

        jLabel13.setText("Tarifa msj multimedia");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 70, 120, 14);

        jLabel14.setText("Tarifa msj texto");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 100, 100, 14);

        jTtarifa_msj_texto1.setText(" ");
        jPanel4.add(jTtarifa_msj_texto1);
        jTtarifa_msj_texto1.setBounds(120, 100, 110, 20);

        jTabbedPane1.addTab("Crear", jPanel4);

        jPanel1.setLayout(null);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "T. otro operador", "T. msj multimedia", "T. msj texto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 100, 470, 125);

        jBConsultar2.setText("Consultar");
        jPanel1.add(jBConsultar2);
        jBConsultar2.setBounds(270, 50, 90, 23);

        jBLimpiar2.setText("Limpiar");
        jPanel1.add(jBLimpiar2);
        jBLimpiar2.setBounds(380, 50, 90, 23);

        jLabel16.setText("Codigo");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 10, 60, 14);
        jPanel1.add(jTFCodigo2);
        jTFCodigo2.setBounds(120, 10, 100, 20);

        jLabel7.setText("Tarifa otro op.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 40, 70, 14);
        jPanel1.add(jTFtarifa_otro_operador2);
        jTFtarifa_otro_operador2.setBounds(120, 40, 110, 20);

        jLabel17.setText("Tarifa msj multimedia");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 70, 120, 14);
        jPanel1.add(jTFtarifa_msj_multimedia2);
        jTFtarifa_msj_multimedia2.setBounds(120, 70, 110, 20);

        jLabel18.setText("Tarifa msj texto");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(270, 10, 100, 14);

        jTtarifa_msj_texto2.setText(" ");
        jPanel1.add(jTtarifa_msj_texto2);
        jTtarifa_msj_texto2.setBounds(380, 10, 110, 20);

        jTabbedPane1.addTab("Consultar", jPanel1);

        jPanel2.setLayout(null);

        jBModificar3.setText("Modificar");
        jPanel2.add(jBModificar3);
        jBModificar3.setBounds(130, 140, 90, 23);
        jPanel2.add(jTFtarifa_msj_multimedia3);
        jTFtarifa_msj_multimedia3.setBounds(120, 70, 110, 20);

        jLabel21.setText("Tarifa msj texto");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 100, 100, 14);

        jTFCodigo3.setEditable(false);
        jTFCodigo3.setEnabled(false);
        jPanel2.add(jTFCodigo3);
        jTFCodigo3.setBounds(120, 10, 100, 20);

        jLabel23.setText("Codigo");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 10, 60, 14);

        jLabel24.setText("Tarifa msj multimedia");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 70, 120, 14);

        jLabel25.setText("Tarifa otro op.");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(10, 40, 70, 14);

        jTtarifa_msj_texto3.setText(" ");
        jPanel2.add(jTtarifa_msj_texto3);
        jTtarifa_msj_texto3.setBounds(120, 100, 110, 20);
        jPanel2.add(jTFtarifa_otro_operador3);
        jTFtarifa_otro_operador3.setBounds(120, 40, 110, 20);

        jTabbedPane1.addTab("Editar", jPanel2);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 500, 260);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked

    }//GEN-LAST:event_jTResultadosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar2;
    private javax.swing.JButton jBCrear1;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiar2;
    private javax.swing.JButton jBModificar3;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigo1;
    private javax.swing.JTextField jTFCodigo2;
    private javax.swing.JTextField jTFCodigo3;
    private javax.swing.JTextField jTFtarifa_msj_multimedia1;
    private javax.swing.JTextField jTFtarifa_msj_multimedia2;
    private javax.swing.JTextField jTFtarifa_msj_multimedia3;
    private javax.swing.JTextField jTFtarifa_otro_operador1;
    private javax.swing.JTextField jTFtarifa_otro_operador2;
    private javax.swing.JTextField jTFtarifa_otro_operador3;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTtarifa_msj_texto1;
    private javax.swing.JTextField jTtarifa_msj_texto2;
    private javax.swing.JTextField jTtarifa_msj_texto3;
    // End of variables declaration//GEN-END:variables
}
