/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.ControladorRecarga;
import controlador.ControladorSimcard;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.Recarga;

/**
 *
 *
 */
public class JPRecarga extends javax.swing.JPanel {

    /**
     * Creates new form JPEquipo
     */
    ControladorRecarga cr;
    ControladorSimcard controladorSimcard;

    public JPRecarga() {
        initComponents();
        cr = new ControladorRecarga();
        controladorSimcard= new ControladorSimcard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTFValor1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBLimpiar1 = new javax.swing.JButton();
        jBCrear1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jCBMedioRecarga1 = new javax.swing.JComboBox();
        jCBSimCard1 = new javax.swing.JComboBox();
        jDCFecha1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jTFNumRecarga1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar2 = new javax.swing.JButton();
        jBLimpiar2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTFValor2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDCFecha2 = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        jCBMedioRecarga2 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jCBSimCard2 = new javax.swing.JComboBox();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Recarga"));
        jPanel3.setLayout(null);

        jPanel4.setLayout(null);

        jLabel9.setText("Valor");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 40, 40, 14);
        jPanel4.add(jTFValor1);
        jTFValor1.setBounds(90, 40, 110, 20);

        jLabel6.setText("Fecha");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 70, 70, 14);

        jLabel8.setText("Simcard");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 130, 90, 14);

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanel4.add(jBLimpiar1);
        jBLimpiar1.setBounds(100, 180, 72, 23);

        jBCrear1.setText("Crear");
        jBCrear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrear1ActionPerformed(evt);
            }
        });
        jPanel4.add(jBCrear1);
        jBCrear1.setBounds(180, 180, 70, 23);

        jLabel13.setText("Medio Recarga");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 100, 90, 14);

        jCBMedioRecarga1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Internet", "Baloto", "Tarjeta" }));
        jCBMedioRecarga1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jCBMedioRecarga1);
        jCBMedioRecarga1.setBounds(90, 100, 150, 20);

        jCBSimCard1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Simcard", " " }));
        jCBSimCard1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCBSimCard1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBSimCard1PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel4.add(jCBSimCard1);
        jCBSimCard1.setBounds(90, 130, 150, 20);

        jDCFecha1.setDateFormatString("yyyy-MMM-dd");
        jPanel4.add(jDCFecha1);
        jDCFecha1.setBounds(90, 70, 150, 20);

        jLabel10.setText("Num. Recarga");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 10, 70, 14);
        jPanel4.add(jTFNumRecarga1);
        jTFNumRecarga1.setBounds(90, 10, 110, 20);

        jTabbedPane1.addTab("Crear", jPanel4);

        jPanel1.setLayout(null);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Valor", "Fecha", "Medio Recarga", "Simcard"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 390, 125);

        jBConsultar2.setText("Consultar");
        jBConsultar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBConsultar2);
        jBConsultar2.setBounds(300, 10, 90, 23);

        jBLimpiar2.setText("Limpiar");
        jBLimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar2);
        jBLimpiar2.setBounds(300, 40, 90, 23);

        jLabel14.setText("Valor");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 10, 40, 14);
        jPanel1.add(jTFValor2);
        jTFValor2.setBounds(90, 10, 110, 20);

        jLabel7.setText("Fecha");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 40, 70, 14);

        jDCFecha2.setDateFormatString("yyyy-MMM-dd");
        jPanel1.add(jDCFecha2);
        jDCFecha2.setBounds(90, 40, 150, 20);

        jLabel15.setText("Medio Recarga");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 70, 90, 14);

        jCBMedioRecarga2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Internet", "Baloto", "Tarjeta" }));
        jCBMedioRecarga2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jCBMedioRecarga2);
        jCBMedioRecarga2.setBounds(90, 70, 150, 20);

        jLabel16.setText("Simcard");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 100, 90, 14);

        jCBSimCard2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Simcard", " " }));
        jCBSimCard2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCBSimCard2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jCBSimCard2PopupMenuWillBecomeVisible(evt);
            }
        });
        jPanel1.add(jCBSimCard2);
        jCBSimCard2.setBounds(90, 100, 150, 20);

        jTabbedPane1.addTab("Consultar", jPanel1);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 420, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrear1ActionPerformed
int guardar = -1;
        try {
            java.sql.Date fecha_recarga = new java.sql.Date(jDCFecha1.getDate().getTime());
            System.out.println(fecha_recarga);
            System.out.println(jCBMedioRecarga1.getSelectedItem().toString());
            System.out.println(jCBSimCard1.getSelectedItem().toString());
            guardar = cr.guardar(
                    Integer.parseInt(jTFNumRecarga1.getText()),
                    Integer.parseInt(jTFValor1.getText()),
                    fecha_recarga,
                    jCBMedioRecarga1.getSelectedItem().toString(),
                    jCBSimCard1.getSelectedItem().toString());
        } catch (Exception e) {
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo crear la Recarga", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        }
        else {
            JOptionPane.showMessageDialog(this, "Recarga Creada correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultar();
            jTFValor2.setText(jTFValor1.getText());
            jDCFecha2.setDate(jDCFecha1.getDate());
            jCBMedioRecarga2.setSelectedItem(jCBMedioRecarga1.getSelectedItem());
            jCBSimCard2.setSelectedItem(jCBSimCard1.getSelectedItem());
            jBConsultar2.doClick();
            jBLimpiar1.doClick();
            jTabbedPane1.setSelectedIndex(1);

        }
   }//GEN-LAST:event_jBCrear1ActionPerformed

    private void jBConsultar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar2ActionPerformed
LinkedList consulta = new LinkedList();
        try {
            consulta = cr.consultar(
                    jTFValor2.getText(),
                    jDCFecha2.getDate().toString(),
                    jCBMedioRecarga2.getSelectedItem().toString(),
                    jCBSimCard2.getSelectedItem().toString());

            Object[][] s = new Object[consulta.size()][4];
            for (int i = 0; i < consulta.size(); i++) {
                Recarga recarga = (Recarga) consulta.get(i);
                if (recarga.getFecha() != null) {
                    s[i][0] = recarga.getValor();
                    s[i][1] = recarga.getFecha();
                    s[i][2] = recarga.getMedio_recarga();
                    s[i][3] = recarga.getSimcard();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"Valor", "Fecha", "Medio de Recarga", "Simcard"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false};

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultar2ActionPerformed

    private void jBLimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar2ActionPerformed
limpiarCamposConsultar();
   }//GEN-LAST:event_jBLimpiar2ActionPerformed

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked
       
    }//GEN-LAST:event_jTResultadosMouseClicked

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
limpiarCamposCrear();        // TODO add your handling code here:
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    private void jCBSimCard2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBSimCard2PopupMenuWillBecomeVisible
 jCBSimCard2.setModel(
                new javax.swing.DefaultComboBoxModel(controladorSimcard.listar()));
          // TODO add your handling code here:
    }//GEN-LAST:event_jCBSimCard2PopupMenuWillBecomeVisible

    private void jCBSimCard1PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jCBSimCard1PopupMenuWillBecomeVisible
     jCBSimCard1.setModel(
                new javax.swing.DefaultComboBoxModel(controladorSimcard.listar()));
     // TODO add your handling code here:
    }//GEN-LAST:event_jCBSimCard1PopupMenuWillBecomeVisible
    

    private void limpiarCamposCrear() {
        jTFValor1.setText("");
        jDCFecha1.setDate(null);
        jCBMedioRecarga1.setSelectedIndex(0);
        jCBSimCard1.setSelectedIndex(0);
        jTFNumRecarga1.setText("");
    }

    private void limpiarCamposConsultar() {
        jTFValor2.setText("");
        jDCFecha2.setDate(null);
        jCBMedioRecarga2.setSelectedIndex(0);
        jCBSimCard2.setSelectedIndex(0);
       
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar2;
    private javax.swing.JButton jBCrear1;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiar2;
    private javax.swing.JComboBox jCBMedioRecarga1;
    private javax.swing.JComboBox jCBMedioRecarga2;
    private javax.swing.JComboBox jCBSimCard1;
    private javax.swing.JComboBox jCBSimCard2;
    private com.toedter.calendar.JDateChooser jDCFecha1;
    private com.toedter.calendar.JDateChooser jDCFecha2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFNumRecarga1;
    private javax.swing.JTextField jTFValor1;
    private javax.swing.JTextField jTFValor2;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
