/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.*;
import java.sql.Time;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.*;

/**
 *
 * @author JUANPAULO
 */
public class JPRoaming extends javax.swing.JPanel {

    /**
     * Creates new form JPRoaming
     */
    ControladorSimcard controladorSimCard;
    ControladorCiaInternacional controladorCiaInter;
    ControladorMensajeSalRoamming controladorSmsSaliente;
    ControladorMensajeEntRoamming controladorSmsEntrante;
    ControladorLlamadaSalRoamming controladorLlamadaSaliente;
    ControladorLlamadaEntRoamming controladorLlamadEntrante;

    public JPRoaming() {
        controladorCiaInter = new ControladorCiaInternacional();
        controladorSimCard = new ControladorSimcard();
        controladorSmsSaliente = new ControladorMensajeSalRoamming();
        controladorSmsEntrante = new ControladorMensajeEntRoamming();
        controladorLlamadaSaliente = new ControladorLlamadaSalRoamming();
        controladorLlamadEntrante = new ControladorLlamadaEntRoamming();
        initComponents();
        llenarJComboBoxCiaInternacional();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar1 = new javax.swing.JButton();
        jBLimpiar1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCBautorizacion_roaming1 = new javax.swing.JComboBox();
        jCBActivacion_Internet1 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jTFnum_telefono1 = new javax.swing.JTextField();
        jTFCodigo1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jCBactivacion_correo1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jCBbloqueado_por_robo1 = new javax.swing.JComboBox();
        jTabbedPaneMensajes = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFSimdCardEnviarMensaje = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jDCFechaEnviarMensaje = new com.toedter.calendar.JDateChooser();
        jLabel36 = new javax.swing.JLabel();
        jCBCompaniaInternacionalEnviarMensaje = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jTFTelDestinoEnviarMensaje = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jBLimpiarEnviarMensaje = new javax.swing.JButton();
        jTFHoraEnviarMensaje = new javax.swing.JTextField();
        jBEnviarMensaje1 = new javax.swing.JButton();
        jBFecha_Hora_ActualEnviarMensaje = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTFSimdCardRecibirMensaje = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jDCFechaRecibirMensaje = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        jCBCompaniaInternacionalRecibirMensaje = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jTFTelOrigenRecibirMensaje = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jBLimpiarRecibirMensaje = new javax.swing.JButton();
        jTFHoraRecibirMensaje = new javax.swing.JTextField();
        jBRecibirMensaje = new javax.swing.JButton();
        jBFecha_Hora_ActualRecibirMensaje = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTFSimdCardConsultarSmsRecibidos = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jDCFechaConsultarSmsRecibidos = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        jCBCompaniaInternacionalConsultarSmsRecibidos = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTResultadosConsultarMsmRecibidos = new javax.swing.JTable();
        jBLimpiarConsultar_Mensajes_Recibidos = new javax.swing.JButton();
        jBConsultarMensajes_Recibidos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTFSimdCardConsultarSmsEnviados = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jDCFechaConsultarSmsEnviados = new com.toedter.calendar.JDateChooser();
        jLabel39 = new javax.swing.JLabel();
        jCBCompaniaInternacionalConsultarSmsEnviados = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTResultadosMensajesEnviados = new javax.swing.JTable();
        jBLimpiarConsultar_Mensajes_Enviados = new javax.swing.JButton();
        jBConsultarMensajes_Enviados = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPaneLlamada = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTFSimdCardRealizarLlamada = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jDCFechaRealizarLlamada = new com.toedter.calendar.JDateChooser();
        jLabel45 = new javax.swing.JLabel();
        jCBCompaniaInternacionalRealizarLlamada = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jTFTelDestinoRealizarLlamada = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTFHoraInicioRealizarLlamada = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTFHoraFinRealizarLlamada = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTFPaisDestinoRealizarLlamada = new javax.swing.JTextField();
        jBLimpiarRealizarLLamada = new javax.swing.JButton();
        jBRealizarLLamada1 = new javax.swing.JButton();
        jBFechaHoraRealizarLlamada = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jTFHoraInicioRecibirLlamada = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jDCFechaRecibirLlamada = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jTFSimdCardRecibirLlamada = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jCBCompaniaInternacionalRecibirLlamada = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jTFTelOrigenRecibirLlamada = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTFHoraFinRecibirLlamada = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTFTPaisOrigenRecibirLlamada = new javax.swing.JTextField();
        jBLimpiarRecibirLLamada = new javax.swing.JButton();
        jBRecibirLLamada1 = new javax.swing.JButton();
        jBFechaHoraRecibirLlamada = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jTFSimdCardConsultarLlamadasRealizadas = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jDCFechaConsultarLlamadasRealizadas = new com.toedter.calendar.JDateChooser();
        jLabel49 = new javax.swing.JLabel();
        jCBCompaniaInternacionalConsultarLlamadasRealizadas = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTResultadosLlamadasRealizadas = new javax.swing.JTable();
        jBLimpiarConsultarLlamadasRealizadas = new javax.swing.JButton();
        jBConsultarLlamadasRealizadas = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTFSimdCardConsultarLlamadasRecibidas = new javax.swing.JTextField();
        jDCFechaConsultarLlamadasRecibidas = new com.toedter.calendar.JDateChooser();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jCBCompaniaInternacionalConsultarLlamadasRecibidas = new javax.swing.JComboBox();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTResultadosLlamadasRecibidas = new javax.swing.JTable();
        jBLimpiarConsultarLlamadasRecibidas = new javax.swing.JButton();
        jBConsultarLlamadasRecibidas = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Romaing"));
        jPanel3.setLayout(null);

        jPanel1.setLayout(null);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Numero Tel", "Internet", "Bloqueado", "Correo", "Roaming"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 490, 125);

        jBConsultar1.setText("Consultar");
        jBConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBConsultar1);
        jBConsultar1.setBounds(260, 100, 100, 23);

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar1);
        jBLimpiar1.setBounds(390, 100, 100, 23);

        jLabel10.setText("Autorizacion Roaming");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(270, 70, 110, 14);

        jLabel11.setText("Numero Tel");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 40, 70, 14);

        jCBautorizacion_roaming1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Autorizado", "Desautorizado" }));
        jPanel1.add(jCBautorizacion_roaming1);
        jCBautorizacion_roaming1.setBounds(390, 70, 100, 20);

        jCBActivacion_Internet1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBActivacion_Internet1);
        jCBActivacion_Internet1.setBounds(130, 70, 100, 20);

        jLabel27.setText("Activacion de Internet");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(10, 70, 140, 14);
        jPanel1.add(jTFnum_telefono1);
        jTFnum_telefono1.setBounds(130, 40, 110, 20);
        jPanel1.add(jTFCodigo1);
        jTFCodigo1.setBounds(130, 10, 100, 20);

        jLabel28.setText("Activacion Correo");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(270, 40, 100, 14);

        jLabel29.setText("Bloqueado por robo");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(270, 10, 100, 14);

        jCBactivacion_correo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBactivacion_correo1);
        jCBactivacion_correo1.setBounds(390, 40, 100, 20);

        jLabel12.setText("Codigo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 10, 60, 14);

        jCBbloqueado_por_robo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBbloqueado_por_robo1);
        jCBbloqueado_por_robo1.setBounds(390, 10, 100, 20);

        jTabbedPane1.addTab("SimCard", jPanel1);

        jPanel6.setLayout(null);

        jLabel16.setText("Telefono Destino");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(10, 100, 100, 14);

        jTFSimdCardEnviarMensaje.setEditable(false);
        jTFSimdCardEnviarMensaje.setEnabled(false);
        jPanel6.add(jTFSimdCardEnviarMensaje);
        jTFSimdCardEnviarMensaje.setBounds(110, 10, 100, 20);

        jLabel35.setText("Cia. Internacional");
        jPanel6.add(jLabel35);
        jLabel35.setBounds(10, 70, 100, 14);

        jDCFechaEnviarMensaje.setDateFormatString("dd MMM yyyy");
        jPanel6.add(jDCFechaEnviarMensaje);
        jDCFechaEnviarMensaje.setBounds(110, 40, 160, 20);

        jLabel36.setText("Hora");
        jPanel6.add(jLabel36);
        jLabel36.setBounds(300, 40, 60, 14);

        jCBCompaniaInternacionalEnviarMensaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel6.add(jCBCompaniaInternacionalEnviarMensaje);
        jCBCompaniaInternacionalEnviarMensaje.setBounds(110, 70, 190, 20);

        jLabel17.setText("SimCard");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(10, 10, 60, 14);
        jPanel6.add(jTFTelDestinoEnviarMensaje);
        jTFTelDestinoEnviarMensaje.setBounds(110, 100, 130, 20);

        jLabel37.setText("Fecha");
        jPanel6.add(jLabel37);
        jLabel37.setBounds(10, 40, 60, 14);

        jBLimpiarEnviarMensaje.setText("Limpiar");
        jBLimpiarEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarEnviarMensajeActionPerformed(evt);
            }
        });
        jPanel6.add(jBLimpiarEnviarMensaje);
        jBLimpiarEnviarMensaje.setBounds(370, 140, 120, 23);
        jPanel6.add(jTFHoraEnviarMensaje);
        jTFHoraEnviarMensaje.setBounds(340, 40, 100, 20);

        jBEnviarMensaje1.setText("Enviar Mensaje");
        jBEnviarMensaje1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarMensaje1ActionPerformed(evt);
            }
        });
        jPanel6.add(jBEnviarMensaje1);
        jBEnviarMensaje1.setBounds(240, 140, 120, 23);

        jBFecha_Hora_ActualEnviarMensaje.setText("Fecha y hora Actual");
        jBFecha_Hora_ActualEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecha_Hora_ActualEnviarMensajeActionPerformed(evt);
            }
        });
        jPanel6.add(jBFecha_Hora_ActualEnviarMensaje);
        jBFecha_Hora_ActualEnviarMensaje.setBounds(320, 70, 150, 23);

        jTabbedPaneMensajes.addTab("Enviar Mensaje", jPanel6);

        jPanel2.setLayout(null);

        jLabel13.setText("Telefono Origen");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 100, 100, 14);

        jTFSimdCardRecibirMensaje.setEditable(false);
        jTFSimdCardRecibirMensaje.setEnabled(false);
        jPanel2.add(jTFSimdCardRecibirMensaje);
        jTFSimdCardRecibirMensaje.setBounds(110, 10, 100, 20);

        jLabel30.setText("Cia. Internacional");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(10, 70, 100, 14);

        jDCFechaRecibirMensaje.setDateFormatString("dd MMM yyyy");
        jPanel2.add(jDCFechaRecibirMensaje);
        jDCFechaRecibirMensaje.setBounds(110, 40, 160, 20);

        jLabel31.setText("Hora");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(300, 40, 60, 14);

        jCBCompaniaInternacionalRecibirMensaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel2.add(jCBCompaniaInternacionalRecibirMensaje);
        jCBCompaniaInternacionalRecibirMensaje.setBounds(110, 70, 190, 20);

        jLabel14.setText("SimCard");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 10, 60, 14);
        jPanel2.add(jTFTelOrigenRecibirMensaje);
        jTFTelOrigenRecibirMensaje.setBounds(110, 100, 130, 20);

        jLabel32.setText("Fecha");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(10, 40, 60, 14);

        jBLimpiarRecibirMensaje.setText("Limpiar");
        jBLimpiarRecibirMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarRecibirMensajeActionPerformed(evt);
            }
        });
        jPanel2.add(jBLimpiarRecibirMensaje);
        jBLimpiarRecibirMensaje.setBounds(370, 140, 120, 23);
        jPanel2.add(jTFHoraRecibirMensaje);
        jTFHoraRecibirMensaje.setBounds(340, 40, 100, 20);

        jBRecibirMensaje.setText("Recibir Mensaje");
        jBRecibirMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRecibirMensajeActionPerformed(evt);
            }
        });
        jPanel2.add(jBRecibirMensaje);
        jBRecibirMensaje.setBounds(240, 140, 120, 23);

        jBFecha_Hora_ActualRecibirMensaje.setText("Fecha y hora Actual");
        jBFecha_Hora_ActualRecibirMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecha_Hora_ActualRecibirMensajeActionPerformed(evt);
            }
        });
        jPanel2.add(jBFecha_Hora_ActualRecibirMensaje);
        jBFecha_Hora_ActualRecibirMensaje.setBounds(320, 70, 150, 23);

        jTabbedPaneMensajes.addTab("Recibir Mensaje", jPanel2);

        jPanel4.setLayout(null);

        jLabel15.setText("SimCard");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 10, 60, 14);
        jPanel4.add(jTFSimdCardConsultarSmsRecibidos);
        jTFSimdCardConsultarSmsRecibidos.setBounds(110, 10, 100, 20);

        jLabel33.setText("Fecha");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(10, 40, 60, 14);

        jDCFechaConsultarSmsRecibidos.setDateFormatString("dd MMM yyyy");
        jPanel4.add(jDCFechaConsultarSmsRecibidos);
        jDCFechaConsultarSmsRecibidos.setBounds(110, 40, 160, 20);

        jLabel34.setText("Cia. Internacional");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(10, 70, 100, 14);

        jCBCompaniaInternacionalConsultarSmsRecibidos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel4.add(jCBCompaniaInternacionalConsultarSmsRecibidos);
        jCBCompaniaInternacionalConsultarSmsRecibidos.setBounds(110, 70, 190, 20);

        jTResultadosConsultarMsmRecibidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SimCard", "Fecha", "Hora", "Cia. Internacional", "Tel. Origen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTResultadosConsultarMsmRecibidos);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 490, 125);

        jBLimpiarConsultar_Mensajes_Recibidos.setText("Limpiar");
        jBLimpiarConsultar_Mensajes_Recibidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultar_Mensajes_RecibidosActionPerformed(evt);
            }
        });
        jPanel4.add(jBLimpiarConsultar_Mensajes_Recibidos);
        jBLimpiarConsultar_Mensajes_Recibidos.setBounds(320, 40, 110, 23);

        jBConsultarMensajes_Recibidos.setText("Consultar");
        jBConsultarMensajes_Recibidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarMensajes_RecibidosActionPerformed(evt);
            }
        });
        jPanel4.add(jBConsultarMensajes_Recibidos);
        jBConsultarMensajes_Recibidos.setBounds(320, 10, 110, 23);

        jTabbedPaneMensajes.addTab("Consultar Mensajes Recibidos", jPanel4);

        jPanel5.setLayout(null);

        jLabel18.setText("SimCard");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(10, 10, 60, 14);
        jPanel5.add(jTFSimdCardConsultarSmsEnviados);
        jTFSimdCardConsultarSmsEnviados.setBounds(110, 10, 100, 20);

        jLabel38.setText("Fecha");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(10, 40, 60, 14);

        jDCFechaConsultarSmsEnviados.setDateFormatString("dd MMM yyyy");
        jPanel5.add(jDCFechaConsultarSmsEnviados);
        jDCFechaConsultarSmsEnviados.setBounds(110, 40, 160, 20);

        jLabel39.setText("Cia. Internacional");
        jPanel5.add(jLabel39);
        jLabel39.setBounds(10, 70, 100, 14);

        jCBCompaniaInternacionalConsultarSmsEnviados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel5.add(jCBCompaniaInternacionalConsultarSmsEnviados);
        jCBCompaniaInternacionalConsultarSmsEnviados.setBounds(110, 70, 190, 20);

        jTResultadosMensajesEnviados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SimCard", "Fecha", "Hora", "Cia. Internacional", "Tel. Destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTResultadosMensajesEnviados);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(10, 110, 490, 125);

        jBLimpiarConsultar_Mensajes_Enviados.setText("Limpiar");
        jBLimpiarConsultar_Mensajes_Enviados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultar_Mensajes_EnviadosActionPerformed(evt);
            }
        });
        jPanel5.add(jBLimpiarConsultar_Mensajes_Enviados);
        jBLimpiarConsultar_Mensajes_Enviados.setBounds(330, 40, 110, 23);

        jBConsultarMensajes_Enviados.setText("Consultar");
        jBConsultarMensajes_Enviados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarMensajes_EnviadosActionPerformed(evt);
            }
        });
        jPanel5.add(jBConsultarMensajes_Enviados);
        jBConsultarMensajes_Enviados.setBounds(330, 10, 110, 23);

        jTabbedPaneMensajes.addTab("Consultar Mensajes Enviados", jPanel5);

        jTabbedPane1.addTab("Mensaje", jTabbedPaneMensajes);

        jPanel7.setLayout(null);

        jPanel8.setLayout(null);

        jLabel22.setText("SimCard");
        jPanel8.add(jLabel22);
        jLabel22.setBounds(10, 10, 60, 14);

        jTFSimdCardRealizarLlamada.setEditable(false);
        jTFSimdCardRealizarLlamada.setEnabled(false);
        jPanel8.add(jTFSimdCardRealizarLlamada);
        jTFSimdCardRealizarLlamada.setBounds(110, 10, 100, 20);

        jLabel44.setText("Fecha");
        jPanel8.add(jLabel44);
        jLabel44.setBounds(10, 40, 60, 14);

        jDCFechaRealizarLlamada.setDateFormatString("dd MMM yyyy");
        jPanel8.add(jDCFechaRealizarLlamada);
        jDCFechaRealizarLlamada.setBounds(110, 40, 160, 20);

        jLabel45.setText("Cia. Internacional");
        jPanel8.add(jLabel45);
        jLabel45.setBounds(10, 70, 100, 14);

        jCBCompaniaInternacionalRealizarLlamada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel8.add(jCBCompaniaInternacionalRealizarLlamada);
        jCBCompaniaInternacionalRealizarLlamada.setBounds(110, 70, 190, 20);

        jLabel23.setText("Telefono Destino");
        jPanel8.add(jLabel23);
        jLabel23.setBounds(10, 100, 100, 14);
        jPanel8.add(jTFTelDestinoRealizarLlamada);
        jTFTelDestinoRealizarLlamada.setBounds(110, 100, 130, 20);

        jLabel46.setText("Hora Inicio");
        jPanel8.add(jLabel46);
        jLabel46.setBounds(320, 40, 70, 14);
        jPanel8.add(jTFHoraInicioRealizarLlamada);
        jTFHoraInicioRealizarLlamada.setBounds(390, 40, 100, 20);

        jLabel47.setText("Hora Fin");
        jPanel8.add(jLabel47);
        jLabel47.setBounds(320, 70, 70, 14);
        jPanel8.add(jTFHoraFinRealizarLlamada);
        jTFHoraFinRealizarLlamada.setBounds(390, 70, 100, 20);

        jLabel24.setText("Pais Destino");
        jPanel8.add(jLabel24);
        jLabel24.setBounds(290, 100, 100, 14);
        jPanel8.add(jTFPaisDestinoRealizarLlamada);
        jTFPaisDestinoRealizarLlamada.setBounds(360, 100, 130, 20);

        jBLimpiarRealizarLLamada.setText("Limpiar");
        jBLimpiarRealizarLLamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarRealizarLLamadaActionPerformed(evt);
            }
        });
        jPanel8.add(jBLimpiarRealizarLLamada);
        jBLimpiarRealizarLLamada.setBounds(320, 160, 130, 23);

        jBRealizarLLamada1.setText("Realizar Llamada");
        jBRealizarLLamada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRealizarLLamada1ActionPerformed(evt);
            }
        });
        jPanel8.add(jBRealizarLLamada1);
        jBRealizarLLamada1.setBounds(140, 160, 130, 23);

        jBFechaHoraRealizarLlamada.setText("Fecha y Hora Actual");
        jBFechaHoraRealizarLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFechaHoraRealizarLlamadaActionPerformed(evt);
            }
        });
        jPanel8.add(jBFechaHoraRealizarLlamada);
        jBFechaHoraRealizarLlamada.setBounds(310, 130, 180, 23);

        jTabbedPaneLlamada.addTab("Realizar LLamada", jPanel8);

        jPanel9.setLayout(null);

        jLabel40.setText("Hora Inicio");
        jPanel9.add(jLabel40);
        jLabel40.setBounds(320, 40, 70, 14);
        jPanel9.add(jTFHoraInicioRecibirLlamada);
        jTFHoraInicioRecibirLlamada.setBounds(390, 40, 100, 20);

        jLabel41.setText("Fecha");
        jPanel9.add(jLabel41);
        jLabel41.setBounds(10, 40, 60, 14);

        jDCFechaRecibirLlamada.setDateFormatString("dd MMM yyyy");
        jPanel9.add(jDCFechaRecibirLlamada);
        jDCFechaRecibirLlamada.setBounds(110, 40, 160, 20);

        jLabel19.setText("SimCard");
        jPanel9.add(jLabel19);
        jLabel19.setBounds(10, 10, 60, 14);

        jTFSimdCardRecibirLlamada.setEditable(false);
        jTFSimdCardRecibirLlamada.setEnabled(false);
        jPanel9.add(jTFSimdCardRecibirLlamada);
        jTFSimdCardRecibirLlamada.setBounds(110, 10, 100, 20);

        jLabel42.setText("Cia. Internacional");
        jPanel9.add(jLabel42);
        jLabel42.setBounds(10, 70, 100, 14);

        jCBCompaniaInternacionalRecibirLlamada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel9.add(jCBCompaniaInternacionalRecibirLlamada);
        jCBCompaniaInternacionalRecibirLlamada.setBounds(110, 70, 190, 20);

        jLabel20.setText("Telefono Origen");
        jPanel9.add(jLabel20);
        jLabel20.setBounds(10, 100, 100, 14);
        jPanel9.add(jTFTelOrigenRecibirLlamada);
        jTFTelOrigenRecibirLlamada.setBounds(110, 100, 130, 20);

        jLabel43.setText("Hora Fin");
        jPanel9.add(jLabel43);
        jLabel43.setBounds(320, 70, 70, 14);
        jPanel9.add(jTFHoraFinRecibirLlamada);
        jTFHoraFinRecibirLlamada.setBounds(390, 70, 100, 20);

        jLabel21.setText("Pais Origen");
        jPanel9.add(jLabel21);
        jLabel21.setBounds(290, 100, 80, 14);
        jPanel9.add(jTFTPaisOrigenRecibirLlamada);
        jTFTPaisOrigenRecibirLlamada.setBounds(360, 100, 130, 20);

        jBLimpiarRecibirLLamada.setText("Limpiar");
        jBLimpiarRecibirLLamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarRecibirLLamadaActionPerformed(evt);
            }
        });
        jPanel9.add(jBLimpiarRecibirLLamada);
        jBLimpiarRecibirLLamada.setBounds(320, 160, 130, 23);

        jBRecibirLLamada1.setText("Recibir Llamada");
        jBRecibirLLamada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRecibirLLamada1ActionPerformed(evt);
            }
        });
        jPanel9.add(jBRecibirLLamada1);
        jBRecibirLLamada1.setBounds(150, 160, 130, 23);

        jBFechaHoraRecibirLlamada.setText("Fecha y Hora Actual");
        jBFechaHoraRecibirLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFechaHoraRecibirLlamadaActionPerformed(evt);
            }
        });
        jPanel9.add(jBFechaHoraRecibirLlamada);
        jBFechaHoraRecibirLlamada.setBounds(310, 130, 180, 23);

        jTabbedPaneLlamada.addTab("Recibir Llamada", jPanel9);

        jPanel10.setLayout(null);

        jLabel25.setText("SimCard");
        jPanel10.add(jLabel25);
        jLabel25.setBounds(10, 10, 60, 14);
        jPanel10.add(jTFSimdCardConsultarLlamadasRealizadas);
        jTFSimdCardConsultarLlamadasRealizadas.setBounds(110, 10, 100, 20);

        jLabel48.setText("Fecha");
        jPanel10.add(jLabel48);
        jLabel48.setBounds(10, 40, 60, 14);

        jDCFechaConsultarLlamadasRealizadas.setDateFormatString("dd MMM yyyy");
        jPanel10.add(jDCFechaConsultarLlamadasRealizadas);
        jDCFechaConsultarLlamadasRealizadas.setBounds(110, 40, 160, 20);

        jLabel49.setText("Cia. Internacional");
        jPanel10.add(jLabel49);
        jLabel49.setBounds(10, 70, 100, 14);

        jCBCompaniaInternacionalConsultarLlamadasRealizadas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel10.add(jCBCompaniaInternacionalConsultarLlamadasRealizadas);
        jCBCompaniaInternacionalConsultarLlamadasRealizadas.setBounds(110, 70, 190, 20);

        jTResultadosLlamadasRealizadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SimCard", "Fecha", "Hora Inicio", "Hora Fin", "Pais Destino", "Tel. Destino", "Cia. Internacional"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTResultadosLlamadasRealizadas);

        jPanel10.add(jScrollPane4);
        jScrollPane4.setBounds(10, 110, 490, 125);

        jBLimpiarConsultarLlamadasRealizadas.setText("Limpiar");
        jBLimpiarConsultarLlamadasRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarLlamadasRealizadasActionPerformed(evt);
            }
        });
        jPanel10.add(jBLimpiarConsultarLlamadasRealizadas);
        jBLimpiarConsultarLlamadasRealizadas.setBounds(330, 40, 120, 23);

        jBConsultarLlamadasRealizadas.setText("Consultar");
        jBConsultarLlamadasRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarLlamadasRealizadasActionPerformed(evt);
            }
        });
        jPanel10.add(jBConsultarLlamadasRealizadas);
        jBConsultarLlamadasRealizadas.setBounds(330, 10, 120, 23);

        jTabbedPaneLlamada.addTab("Consultar Llamadas Realizadas", jPanel10);

        jPanel11.setLayout(null);

        jLabel26.setText("SimCard");
        jPanel11.add(jLabel26);
        jLabel26.setBounds(10, 10, 60, 14);
        jPanel11.add(jTFSimdCardConsultarLlamadasRecibidas);
        jTFSimdCardConsultarLlamadasRecibidas.setBounds(110, 10, 100, 20);

        jDCFechaConsultarLlamadasRecibidas.setDateFormatString("dd MMM yyyy");
        jPanel11.add(jDCFechaConsultarLlamadasRecibidas);
        jDCFechaConsultarLlamadasRecibidas.setBounds(110, 40, 160, 20);

        jLabel50.setText("Fecha");
        jPanel11.add(jLabel50);
        jLabel50.setBounds(10, 40, 60, 14);

        jLabel51.setText("Cia. Internacional");
        jPanel11.add(jLabel51);
        jLabel51.setBounds(10, 70, 100, 14);

        jCBCompaniaInternacionalConsultarLlamadasRecibidas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel11.add(jCBCompaniaInternacionalConsultarLlamadasRecibidas);
        jCBCompaniaInternacionalConsultarLlamadasRecibidas.setBounds(110, 70, 190, 20);

        jTResultadosLlamadasRecibidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SimCard", "Hora Inicio", "Fecha", "Cia. Internacional", "Pais Origen", "Tel. Origen", "Hora Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTResultadosLlamadasRecibidas);

        jPanel11.add(jScrollPane5);
        jScrollPane5.setBounds(10, 110, 490, 125);

        jBLimpiarConsultarLlamadasRecibidas.setText("Limpiar");
        jBLimpiarConsultarLlamadasRecibidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarConsultarLlamadasRecibidasActionPerformed(evt);
            }
        });
        jPanel11.add(jBLimpiarConsultarLlamadasRecibidas);
        jBLimpiarConsultarLlamadasRecibidas.setBounds(330, 40, 120, 23);

        jBConsultarLlamadasRecibidas.setText("Consultar");
        jBConsultarLlamadasRecibidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarLlamadasRecibidasActionPerformed(evt);
            }
        });
        jPanel11.add(jBConsultarLlamadasRecibidas);
        jBConsultarLlamadasRecibidas.setBounds(330, 10, 120, 23);

        jTabbedPaneLlamada.addTab("Consultar Llamadas Recibidas", jPanel11);

        jPanel7.add(jTabbedPaneLlamada);
        jTabbedPaneLlamada.setBounds(0, 0, 510, 270);

        jTabbedPane1.addTab("Llamada", jPanel7);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 520, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked
        int selectedRow = jTResultados.getSelectedRow();
        jTFSimdCardEnviarMensaje.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTFSimdCardRecibirMensaje.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTFSimdCardRealizarLlamada.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTFSimdCardRecibirLlamada.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jTResultadosMouseClicked

    private void jBConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar1ActionPerformed
        // TODO add your handling code here:
        LinkedList consulta = new LinkedList();
        try {

            consulta = controladorSimCard.consultar(
                    jTFCodigo1.getText(),
                    jTFnum_telefono1.getText(),
                    jCBActivacion_Internet1.getSelectedItem().toString(),
                    jCBbloqueado_por_robo1.getSelectedItem().toString(),
                    jCBactivacion_correo1.getSelectedItem().toString(),
                    jCBautorizacion_roaming1.getSelectedItem().toString());

            Object[][] s = new Object[consulta.size()][6];
            for (int i = 0; i < consulta.size(); i++) {
                Simcard sim = (Simcard) consulta.get(i);
                if (sim.getCodigo() != null) {
                    s[i][0] = sim.getCodigo();
                    s[i][1] = sim.getNum_telefono();
                    s[i][2] = sim.getActivacion_internet();
                    s[i][3] = sim.getBloqueado_por_robo();
                    s[i][4] = sim.getActivacion_correo();
                    s[i][5] = sim.getAutorizacion_roaming();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"Codigo", "Numero Tel", "Internet", "Bloqueado", "Correo", "Roaming"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultar1ActionPerformed

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed
        limpiarCamposSimCard();
        jBConsultar1.doClick();
    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    private void jBLimpiarRecibirMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarRecibirMensajeActionPerformed
        limpiarCamposRecibirMensaje();
    }//GEN-LAST:event_jBLimpiarRecibirMensajeActionPerformed

    private void jBLimpiarEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarEnviarMensajeActionPerformed
        limpiarCamposEnviarMensaje();
    }//GEN-LAST:event_jBLimpiarEnviarMensajeActionPerformed

    private void jBEnviarMensaje1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarMensaje1ActionPerformed
        int guardar = -1;
        try {
            java.sql.Date fecha = new java.sql.Date(jDCFechaEnviarMensaje.getDate().getTime());
            String codigo_CiaInter[] = new String[2];
            codigo_CiaInter = jCBCompaniaInternacionalEnviarMensaje.getSelectedItem().toString().split(" - ");
            String[] hora = jTFHoraEnviarMensaje.getText().split(":");
            guardar = controladorSmsSaliente.guardar(
                    jTFSimdCardEnviarMensaje.getText(),
                    fecha,
                    new Time(Integer.parseInt(hora[0]), Integer.parseInt(hora[1]), Integer.parseInt(hora[2])),
                    codigo_CiaInter[0],
                    jTFTelDestinoEnviarMensaje.getText());

        } catch (Exception e) {
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo Enviar el mensaje", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Mensaje Enviado correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultarMensajesEnviados();
            jTFSimdCardConsultarSmsEnviados.setText(jTFSimdCardEnviarMensaje.getText());
            jBConsultarMensajes_Enviados.doClick();
            jBLimpiarEnviarMensaje.doClick();
            jTabbedPaneMensajes.setSelectedIndex(3);

        }
    }//GEN-LAST:event_jBEnviarMensaje1ActionPerformed

    private void jBRecibirMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRecibirMensajeActionPerformed
        int guardar = -1;
        try {
            java.sql.Date fecha = new java.sql.Date(jDCFechaRecibirMensaje.getDate().getTime());
            String codigo_CiaInter[] = new String[2];
            codigo_CiaInter = jCBCompaniaInternacionalRecibirMensaje.getSelectedItem().toString().split(" - ");
            String[] hora = jTFHoraRecibirMensaje.getText().split(":");
            guardar = controladorSmsEntrante.guardar(
                    jTFSimdCardRecibirMensaje.getText(),
                    fecha,
                    new Time(Integer.parseInt(hora[0]), Integer.parseInt(hora[1]), Integer.parseInt(hora[2])),
                    codigo_CiaInter[0],
                    jTFTelOrigenRecibirMensaje.getText());

        } catch (Exception e) {
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo Recibir el mensaje", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Mensaje Recibido correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultarMensajesRecibidos();
            jTFSimdCardConsultarSmsRecibidos.setText(jTFSimdCardRecibirMensaje.getText());
            jBConsultarMensajes_Recibidos.doClick();
            jBLimpiarRecibirMensaje.doClick();
            jTabbedPaneMensajes.setSelectedIndex(2);
        }
    }//GEN-LAST:event_jBRecibirMensajeActionPerformed

    private void jBFecha_Hora_ActualEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecha_Hora_ActualEnviarMensajeActionPerformed
        jDCFechaEnviarMensaje.setDate(fechaActual());
        jTFHoraEnviarMensaje.setText(horaActual());
    }//GEN-LAST:event_jBFecha_Hora_ActualEnviarMensajeActionPerformed

    private void jBLimpiarConsultar_Mensajes_RecibidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultar_Mensajes_RecibidosActionPerformed
        limpiarCamposConsultarMensajesRecibidos();
        jBConsultarMensajes_Recibidos.doClick();
    }//GEN-LAST:event_jBLimpiarConsultar_Mensajes_RecibidosActionPerformed

    private void jBLimpiarConsultar_Mensajes_EnviadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultar_Mensajes_EnviadosActionPerformed
        limpiarCamposConsultarMensajesEnviados();
        jBConsultarMensajes_Enviados.doClick();
    }//GEN-LAST:event_jBLimpiarConsultar_Mensajes_EnviadosActionPerformed

    private void jBFecha_Hora_ActualRecibirMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecha_Hora_ActualRecibirMensajeActionPerformed
        jDCFechaRecibirMensaje.setDate(fechaActual());
        jTFHoraRecibirMensaje.setText(horaActual());
    }//GEN-LAST:event_jBFecha_Hora_ActualRecibirMensajeActionPerformed

    private void jBConsultarMensajes_RecibidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarMensajes_RecibidosActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            String fecha;
            try {
                fecha = new java.sql.Date(jDCFechaConsultarSmsRecibidos.getDate().getTime()).toString();

            } catch (Exception e) {
                fecha = "";
            }
            String cia_Inte = "";
            if (!jCBCompaniaInternacionalConsultarSmsRecibidos.getSelectedItem().toString().equals(" ")) {
                String codigo_CiaInter[] = new String[2];
                codigo_CiaInter = jCBCompaniaInternacionalConsultarSmsRecibidos.getSelectedItem().toString().split(" - ");
                cia_Inte = codigo_CiaInter[0];
            }

            consulta = controladorSmsEntrante.consultar(jTFSimdCardConsultarSmsRecibidos.getText(),
                    fecha,
                    cia_Inte,
                    "");

            Object[][] s = new Object[consulta.size()][6];
            for (int i = 0; i < consulta.size(); i++) {
                MensajeEntRoamming msr = (MensajeEntRoamming) consulta.get(i);
                if (msr.getSim() != null) {
                    s[i][0] = msr.getSim().getCodigo();
                    s[i][1] = msr.getFecha();
                    s[i][2] = msr.getHora();
                    s[i][3] = msr.getcInter().getId();
                    s[i][4] = msr.getTel_Origen();
                    s[i][5] = controladorCiaInter.consultar(msr.getcInter().getId()).getNombre();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"SimCard", "Fecha", "Hora", "Cia. Inter.", "Tel. Origen", "Nom. Cia. Inter."}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosConsultarMsmRecibidos.setModel(myModel);
            jTResultadosConsultarMsmRecibidos.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarMensajes_RecibidosActionPerformed

    private void jBConsultarMensajes_EnviadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarMensajes_EnviadosActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            String fecha;
            try {
                fecha = new java.sql.Date(jDCFechaConsultarSmsEnviados.getDate().getTime()).toString();

            } catch (Exception e) {
                fecha = "";
            }
            String cia_Inte = "";
            if (!jCBCompaniaInternacionalConsultarSmsEnviados.getSelectedItem().toString().equals(" ")) {
                String codigo_CiaInter[] = new String[2];
                codigo_CiaInter = jCBCompaniaInternacionalConsultarSmsEnviados.getSelectedItem().toString().split(" - ");
                cia_Inte = codigo_CiaInter[0];
            }

            consulta = controladorSmsSaliente.consultar(jTFSimdCardConsultarSmsEnviados.getText(),
                    fecha,
                    cia_Inte,
                    "");

            Object[][] s = new Object[consulta.size()][6];
            for (int i = 0; i < consulta.size(); i++) {
                MensajeSalRoamming msr = (MensajeSalRoamming) consulta.get(i);
                if (msr.getSim() != null) {
                    s[i][0] = msr.getSim().getCodigo();
                    s[i][1] = msr.getFecha();
                    s[i][2] = msr.getHora();
                    s[i][3] = msr.getcInter().getId();
                    s[i][4] = msr.getTel_destino();
                    s[i][5] = controladorCiaInter.consultar(msr.getcInter().getId()).getNombre();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"SimCard", "Fecha", "Hora", "Cia. Inter.", "Tel. Destino", "Nom. Cia. Inter."}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosMensajesEnviados.setModel(myModel);
            jTResultadosMensajesEnviados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarMensajes_EnviadosActionPerformed

    private void jBLimpiarRealizarLLamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarRealizarLLamadaActionPerformed
        limpiarCamposRealizarLlamada();
    }//GEN-LAST:event_jBLimpiarRealizarLLamadaActionPerformed

    private void jBLimpiarRecibirLLamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarRecibirLLamadaActionPerformed
        limpiarCamposRecibirLlamada();
    }//GEN-LAST:event_jBLimpiarRecibirLLamadaActionPerformed

    private void jBFechaHoraRealizarLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFechaHoraRealizarLlamadaActionPerformed
        jDCFechaRealizarLlamada.setDate(fechaActual());
        jTFHoraInicioRealizarLlamada.setText(horaActual());
    }//GEN-LAST:event_jBFechaHoraRealizarLlamadaActionPerformed

    private void jBRealizarLLamada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRealizarLLamada1ActionPerformed
        int guardar = -1;
        try {
            java.sql.Date fecha = new java.sql.Date(jDCFechaRealizarLlamada.getDate().getTime());
            String codigo_CiaInter[] = new String[2];
            codigo_CiaInter = jCBCompaniaInternacionalRealizarLlamada.getSelectedItem().toString().split(" - ");
            String[] horainicio = jTFHoraInicioRealizarLlamada.getText().split(":");
            String[] horafin = jTFHoraInicioRealizarLlamada.getText().split(":");
            guardar = controladorLlamadaSaliente.guardar(
                    jTFSimdCardRealizarLlamada.getText(),
                    fecha,
                    new Time(Integer.parseInt(horainicio[0]), Integer.parseInt(horainicio[1]), Integer.parseInt(horainicio[2])),
                    new Time(Integer.parseInt(horafin[0]), Integer.parseInt(horafin[1]), Integer.parseInt(horafin[2])),
                    jTFPaisDestinoRealizarLlamada.getText(),
                    jTFTelDestinoRealizarLlamada.getText(),
                    codigo_CiaInter[0]);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo Realizar la llamada", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Llamada realizada correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultarLlamadasRealizadas();
            jTFSimdCardConsultarLlamadasRealizadas.setText(jTFSimdCardRealizarLlamada.getText());
            jBConsultarLlamadasRealizadas.doClick();
            jBLimpiarRealizarLLamada.doClick();
            jTabbedPaneLlamada.setSelectedIndex(2);

        }
    }//GEN-LAST:event_jBRealizarLLamada1ActionPerformed

    private void jBLimpiarConsultarLlamadasRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarLlamadasRealizadasActionPerformed
        limpiarCamposConsultarLlamadasRealizadas();
        jBConsultarLlamadasRealizadas.doClick();
    }//GEN-LAST:event_jBLimpiarConsultarLlamadasRealizadasActionPerformed

    private void jBConsultarLlamadasRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarLlamadasRealizadasActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            String fecha;
            try {
                fecha = new java.sql.Date(jDCFechaConsultarLlamadasRealizadas.getDate().getTime()).toString();

            } catch (Exception e) {
                fecha = "";
            }
            String cia_Inte = "";
            if (!jCBCompaniaInternacionalConsultarLlamadasRealizadas.getSelectedItem().toString().equals(" ")) {
                String codigo_CiaInter[] = new String[2];
                codigo_CiaInter = jCBCompaniaInternacionalConsultarLlamadasRealizadas.getSelectedItem().toString().split(" - ");
                cia_Inte = codigo_CiaInter[0];
            }

            consulta = controladorLlamadaSaliente.consultar(
                    jTFSimdCardConsultarLlamadasRealizadas.getText(),
                    fecha,
                    "",
                    "",
                    "",
                    "",
                    cia_Inte);

            Object[][] s = new Object[consulta.size()][8];
            for (int i = 0; i < consulta.size(); i++) {
                LlamadaSalRoamming lsr = (LlamadaSalRoamming) consulta.get(i);
                if (lsr.getSim() != null) {
                    s[i][0] = lsr.getSim().getCodigo();
                    s[i][1] = lsr.getFecha();
                    s[i][2] = lsr.getHora_inicio();
                    s[i][3] = lsr.getHora_fin();
                    s[i][4] = lsr.getPais_destino();
                    s[i][5] = lsr.getTel_destino();
                    s[i][6] = lsr.getcInter().getId();
                    s[i][7] = controladorCiaInter.consultar(lsr.getcInter().getId()).getNombre();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"SimCard", "Fecha", "Hora Inicio", "Hora Fin", "Pais Dest.", "Tel. Dest.", "Cia. Inter", "Nom. Cia. Inter."}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosLlamadasRealizadas.setModel(myModel);
            jTResultadosLlamadasRealizadas.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarLlamadasRealizadasActionPerformed

    private void jBFechaHoraRecibirLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFechaHoraRecibirLlamadaActionPerformed
        jDCFechaRecibirLlamada.setDate(fechaActual());
        jTFHoraInicioRecibirLlamada.setText(horaActual());
    }//GEN-LAST:event_jBFechaHoraRecibirLlamadaActionPerformed

    private void jBConsultarLlamadasRecibidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarLlamadasRecibidasActionPerformed
        LinkedList consulta = new LinkedList();
        try {
            String fecha;
            try {
                fecha = new java.sql.Date(jDCFechaConsultarLlamadasRecibidas.getDate().getTime()).toString();

            } catch (Exception e) {
                fecha = "";
            }
            String cia_Inte = "";
            if (!jCBCompaniaInternacionalConsultarLlamadasRecibidas.getSelectedItem().toString().equals(" ")) {
                String codigo_CiaInter[] = new String[2];
                codigo_CiaInter = jCBCompaniaInternacionalConsultarLlamadasRecibidas.getSelectedItem().toString().split(" - ");
                cia_Inte = codigo_CiaInter[0];
            }

            consulta = controladorLlamadEntrante.consultar(
                    jTFSimdCardConsultarLlamadasRealizadas.getText(),
                    fecha,
                    "",
                    "",
                    "",
                    "",
                    cia_Inte);

            Object[][] s = new Object[consulta.size()][8];
            for (int i = 0; i < consulta.size(); i++) {
                LlamadaEntRoamming lsr = (LlamadaEntRoamming) consulta.get(i);
                if (lsr.getSim() != null) {
                    s[i][0] = lsr.getSim().getCodigo();
                    s[i][1] = lsr.getFecha();
                    s[i][2] = lsr.getHora_inicio();
                    s[i][3] = lsr.getHora_fin();
                    s[i][4] = lsr.getpais_origen();
                    s[i][5] = lsr.getTel_Origen();
                    s[i][6] = lsr.getcInter().getId();
                    s[i][7] = controladorCiaInter.consultar(lsr.getcInter().getId()).getNombre();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"SimCard", "Fecha", "Hora Inicio", "Hora Fin", "Pais Dest.", "Tel. Origen", "Cia. Inter", "Nom. Cia. Inter."}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultadosLlamadasRecibidas.setModel(myModel);
            jTResultadosLlamadasRecibidas.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultarLlamadasRecibidasActionPerformed

    private void jBRecibirLLamada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRecibirLLamada1ActionPerformed
        int guardar = -1;
        try {
            java.sql.Date fecha = new java.sql.Date(jDCFechaRecibirLlamada.getDate().getTime());
            String codigo_CiaInter[] = new String[2];
            codigo_CiaInter = jCBCompaniaInternacionalRecibirLlamada.getSelectedItem().toString().split(" - ");
            String[] horainicio = jTFHoraInicioRecibirLlamada.getText().split(":");
            String[] horafin = jTFHoraInicioRecibirLlamada.getText().split(":");
            guardar = controladorLlamadEntrante.guardar(
                    jTFSimdCardRecibirLlamada.getText(),
                    fecha,
                    new Time(Integer.parseInt(horainicio[0]), Integer.parseInt(horainicio[1]), Integer.parseInt(horainicio[2])),
                    new Time(Integer.parseInt(horafin[0]), Integer.parseInt(horafin[1]), Integer.parseInt(horafin[2])),
                    jTFTPaisOrigenRecibirLlamada.getText(),
                    jTFTelOrigenRecibirLlamada.getText(),
                    codigo_CiaInter[0]);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        if (guardar == -1) {
            JOptionPane.showMessageDialog(this, "No su pudo Recibir la llamada", "Error Base Datos", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Llamada Recibir correctamente", "Base Datos", JOptionPane.INFORMATION_MESSAGE);
            limpiarCamposConsultarLlamadasRecibidas();
            jTFSimdCardConsultarLlamadasRecibidas.setText(jTFSimdCardRecibirLlamada.getText());
            jBConsultarLlamadasRecibidas.doClick();
            jBLimpiarRecibirLLamada.doClick();
            jTabbedPaneLlamada.setSelectedIndex(3);

        }
    }//GEN-LAST:event_jBRecibirLLamada1ActionPerformed

    private void jBLimpiarConsultarLlamadasRecibidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarConsultarLlamadasRecibidasActionPerformed
        limpiarCamposConsultarLlamadasRecibidas();
        jBConsultarLlamadasRecibidas.doClick();
    }//GEN-LAST:event_jBLimpiarConsultarLlamadasRecibidasActionPerformed

    private Date fechaActual() {
        return new Date();
    }

    private String horaActual() {
        String hora = "";
        Calendar c = Calendar.getInstance();
        hora = c.get(Calendar.HOUR_OF_DAY) + ":" + c.get(Calendar.MINUTE) + ":" + c.get(Calendar.SECOND);
        return hora;
    }

    private void limpiarCamposSimCard() {
        jTFCodigo1.setText("");
        jTFnum_telefono1.setText("");
        jCBActivacion_Internet1.setSelectedIndex(0);
        jCBbloqueado_por_robo1.setSelectedIndex(0);
        jCBactivacion_correo1.setSelectedIndex(0);
        jCBautorizacion_roaming1.setSelectedIndex(0);
    }

    private void limpiarCamposEnviarMensaje() {
        jDCFechaEnviarMensaje.setDate(null);
        jTFHoraEnviarMensaje.setText("");
        jCBCompaniaInternacionalEnviarMensaje.setSelectedIndex(0);
        jTFTelDestinoEnviarMensaje.setText("");
    }

    private void limpiarCamposRecibirMensaje() {
        jDCFechaRecibirMensaje.setDate(null);
        jTFHoraRecibirMensaje.setText("");
        jCBCompaniaInternacionalRecibirMensaje.setSelectedIndex(0);
        jTFTelOrigenRecibirMensaje.setText("");
    }

    private void limpiarCamposConsultarMensajesRecibidos() {
        jTFSimdCardConsultarSmsRecibidos.setText("");
        jDCFechaConsultarSmsRecibidos.setDate(null);
        jCBCompaniaInternacionalConsultarSmsRecibidos.setSelectedIndex(0);
    }

    private void limpiarCamposConsultarMensajesEnviados() {
        jTFSimdCardConsultarSmsEnviados.setText("");
        jDCFechaConsultarSmsEnviados.setDate(null);
        jCBCompaniaInternacionalConsultarSmsEnviados.setSelectedIndex(0);
    }

    private void limpiarCamposRealizarLlamada() {
        jDCFechaRealizarLlamada.setDate(null);
        jCBCompaniaInternacionalRealizarLlamada.setSelectedIndex(0);
        jTFHoraInicioRealizarLlamada.setText("");
        jTFHoraFinRealizarLlamada.setText("");
        jTFTelDestinoRealizarLlamada.setText("");
        jTFPaisDestinoRealizarLlamada.setText("");
    }

    private void limpiarCamposRecibirLlamada() {
        jDCFechaRecibirLlamada.setDate(null);
        jCBCompaniaInternacionalRecibirLlamada.setSelectedIndex(0);
        jTFHoraInicioRecibirLlamada.setText("");
        jTFHoraFinRecibirLlamada.setText("");
        jTFTelOrigenRecibirLlamada.setText("");
        jTFTPaisOrigenRecibirLlamada.setText("");
    }

    private void limpiarCamposConsultarLlamadasRealizadas() {
        jTFSimdCardConsultarLlamadasRealizadas.setText("");
        jDCFechaConsultarLlamadasRealizadas.setDate(null);
        jCBCompaniaInternacionalConsultarLlamadasRealizadas.setSelectedIndex(0);
    }

    private void limpiarCamposConsultarLlamadasRecibidas() {
        jTFSimdCardConsultarLlamadasRecibidas.setText("");
        jDCFechaConsultarLlamadasRecibidas.setDate(null);
        jCBCompaniaInternacionalConsultarLlamadasRecibidas.setSelectedIndex(0);
    }

    private void llenarJComboBoxCiaInternacional() {  //llenar JComboBox
        jCBCompaniaInternacionalConsultarLlamadasRealizadas.setModel(
                new javax.swing.DefaultComboBoxModel(controladorCiaInter.listar()));
        jCBCompaniaInternacionalRecibirMensaje.setModel(
                new javax.swing.DefaultComboBoxModel(controladorCiaInter.listar()));
        jCBCompaniaInternacionalEnviarMensaje.setModel(
                new javax.swing.DefaultComboBoxModel(controladorCiaInter.listar()));
        jCBCompaniaInternacionalConsultarSmsRecibidos.setModel(
                new javax.swing.DefaultComboBoxModel(controladorCiaInter.listar()));
        jCBCompaniaInternacionalConsultarSmsEnviados.setModel(
                new javax.swing.DefaultComboBoxModel(controladorCiaInter.listar()));
        jCBCompaniaInternacionalConsultarLlamadasRecibidas.setModel(
                new javax.swing.DefaultComboBoxModel(controladorCiaInter.listar()));
        jCBCompaniaInternacionalRecibirLlamada.setModel(
                new javax.swing.DefaultComboBoxModel(controladorCiaInter.listar()));
        jCBCompaniaInternacionalRealizarLlamada.setModel(
                new javax.swing.DefaultComboBoxModel(controladorCiaInter.listar()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar1;
    private javax.swing.JButton jBConsultarLlamadasRealizadas;
    private javax.swing.JButton jBConsultarLlamadasRecibidas;
    private javax.swing.JButton jBConsultarMensajes_Enviados;
    private javax.swing.JButton jBConsultarMensajes_Recibidos;
    private javax.swing.JButton jBEnviarMensaje1;
    private javax.swing.JButton jBFechaHoraRealizarLlamada;
    private javax.swing.JButton jBFechaHoraRecibirLlamada;
    private javax.swing.JButton jBFecha_Hora_ActualEnviarMensaje;
    private javax.swing.JButton jBFecha_Hora_ActualRecibirMensaje;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiarConsultarLlamadasRealizadas;
    private javax.swing.JButton jBLimpiarConsultarLlamadasRecibidas;
    private javax.swing.JButton jBLimpiarConsultar_Mensajes_Enviados;
    private javax.swing.JButton jBLimpiarConsultar_Mensajes_Recibidos;
    private javax.swing.JButton jBLimpiarEnviarMensaje;
    private javax.swing.JButton jBLimpiarRealizarLLamada;
    private javax.swing.JButton jBLimpiarRecibirLLamada;
    private javax.swing.JButton jBLimpiarRecibirMensaje;
    private javax.swing.JButton jBRealizarLLamada1;
    private javax.swing.JButton jBRecibirLLamada1;
    private javax.swing.JButton jBRecibirMensaje;
    private javax.swing.JComboBox jCBActivacion_Internet1;
    private javax.swing.JComboBox jCBCompaniaInternacionalConsultarLlamadasRealizadas;
    private javax.swing.JComboBox jCBCompaniaInternacionalConsultarLlamadasRecibidas;
    private javax.swing.JComboBox jCBCompaniaInternacionalConsultarSmsEnviados;
    private javax.swing.JComboBox jCBCompaniaInternacionalConsultarSmsRecibidos;
    private javax.swing.JComboBox jCBCompaniaInternacionalEnviarMensaje;
    private javax.swing.JComboBox jCBCompaniaInternacionalRealizarLlamada;
    private javax.swing.JComboBox jCBCompaniaInternacionalRecibirLlamada;
    private javax.swing.JComboBox jCBCompaniaInternacionalRecibirMensaje;
    private javax.swing.JComboBox jCBactivacion_correo1;
    private javax.swing.JComboBox jCBautorizacion_roaming1;
    private javax.swing.JComboBox jCBbloqueado_por_robo1;
    private com.toedter.calendar.JDateChooser jDCFechaConsultarLlamadasRealizadas;
    private com.toedter.calendar.JDateChooser jDCFechaConsultarLlamadasRecibidas;
    private com.toedter.calendar.JDateChooser jDCFechaConsultarSmsEnviados;
    private com.toedter.calendar.JDateChooser jDCFechaConsultarSmsRecibidos;
    private com.toedter.calendar.JDateChooser jDCFechaEnviarMensaje;
    private com.toedter.calendar.JDateChooser jDCFechaRealizarLlamada;
    private com.toedter.calendar.JDateChooser jDCFechaRecibirLlamada;
    private com.toedter.calendar.JDateChooser jDCFechaRecibirMensaje;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTFCodigo1;
    private javax.swing.JTextField jTFHoraEnviarMensaje;
    private javax.swing.JTextField jTFHoraFinRealizarLlamada;
    private javax.swing.JTextField jTFHoraFinRecibirLlamada;
    private javax.swing.JTextField jTFHoraInicioRealizarLlamada;
    private javax.swing.JTextField jTFHoraInicioRecibirLlamada;
    private javax.swing.JTextField jTFHoraRecibirMensaje;
    private javax.swing.JTextField jTFPaisDestinoRealizarLlamada;
    private javax.swing.JTextField jTFSimdCardConsultarLlamadasRealizadas;
    private javax.swing.JTextField jTFSimdCardConsultarLlamadasRecibidas;
    private javax.swing.JTextField jTFSimdCardConsultarSmsEnviados;
    private javax.swing.JTextField jTFSimdCardConsultarSmsRecibidos;
    private javax.swing.JTextField jTFSimdCardEnviarMensaje;
    private javax.swing.JTextField jTFSimdCardRealizarLlamada;
    private javax.swing.JTextField jTFSimdCardRecibirLlamada;
    private javax.swing.JTextField jTFSimdCardRecibirMensaje;
    private javax.swing.JTextField jTFTPaisOrigenRecibirLlamada;
    private javax.swing.JTextField jTFTelDestinoEnviarMensaje;
    private javax.swing.JTextField jTFTelDestinoRealizarLlamada;
    private javax.swing.JTextField jTFTelOrigenRecibirLlamada;
    private javax.swing.JTextField jTFTelOrigenRecibirMensaje;
    private javax.swing.JTextField jTFnum_telefono1;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTable jTResultadosConsultarMsmRecibidos;
    private javax.swing.JTable jTResultadosLlamadasRealizadas;
    private javax.swing.JTable jTResultadosLlamadasRecibidas;
    private javax.swing.JTable jTResultadosMensajesEnviados;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneLlamada;
    private javax.swing.JTabbedPane jTabbedPaneMensajes;
    // End of variables declaration//GEN-END:variables
}
