/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.ControladorSimcard;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.Simcard;

/**
 *
 * @author JUANPAULO
 */
public class JPRoaming extends javax.swing.JPanel {

    /**
     * Creates new form JPRoaming
     */
    ControladorSimcard cs;
    public JPRoaming() {
        cs = new ControladorSimcard();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar1 = new javax.swing.JButton();
        jBLimpiar1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCBautorizacion_roaming1 = new javax.swing.JComboBox();
        jCBActivacion_Internet1 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jTFnum_telefono1 = new javax.swing.JTextField();
        jTFCodigo1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jCBactivacion_correo1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jCBbloqueado_por_robo1 = new javax.swing.JComboBox();
        jTabbedPaneMensajes = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTFSimdCardEnviarMensaje = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jDCFechaEnviarMensaje = new com.toedter.calendar.JDateChooser();
        jLabel36 = new javax.swing.JLabel();
        jCBCompaniaInternacionalEnviarMensaje = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jTFTelDestinoEnviarMensaje = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jBEnviarMensaje = new javax.swing.JButton();
        jTFHoraEnviarMensaje = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTFSimdCardRecibirMensaje = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jDCFechaRecibirMensaje = new com.toedter.calendar.JDateChooser();
        jLabel31 = new javax.swing.JLabel();
        jCBCompaniaInternacionalRecibirMensaje = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jTFTelOrigenRecibirMensaje = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTFHoraRecibirMensaje = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTFSimdCardConsultarMsmRecibidos = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jDCFechaConsultarMsmRecibidos = new com.toedter.calendar.JDateChooser();
        jLabel34 = new javax.swing.JLabel();
        jCBCompaniaInternacionalConsultarMsmRecibidos = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTResultadosConsultarMsmRecibidos = new javax.swing.JTable();
        jBConsultarMensajes_Recibidos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTFSimdCardConsultarMsmEnviados = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jDCFechaConsultarMsmEnviados = new com.toedter.calendar.JDateChooser();
        jLabel39 = new javax.swing.JLabel();
        jCBCompaniaInternacionalConsultarMsmEnviados = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTResultadosMensajesEnviados = new javax.swing.JTable();
        jBConsultarMensajes_Enviados = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Romaing"));
        jPanel3.setLayout(null);

        jPanel1.setLayout(null);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Numero Tel", "Internet", "Bloqueado", "Correo", "Roaming"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 490, 125);

        jBConsultar1.setText("Consultar");
        jBConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBConsultar1);
        jBConsultar1.setBounds(260, 100, 100, 23);

        jBLimpiar1.setText("Limpiar");
        jBLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBLimpiar1);
        jBLimpiar1.setBounds(390, 100, 100, 23);

        jLabel10.setText("Autorizacion Roaming");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(270, 70, 110, 14);

        jLabel11.setText("Numero Tel");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 40, 70, 14);

        jCBautorizacion_roaming1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Autorizado", "Desautorizado" }));
        jPanel1.add(jCBautorizacion_roaming1);
        jCBautorizacion_roaming1.setBounds(390, 70, 100, 20);

        jCBActivacion_Internet1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBActivacion_Internet1);
        jCBActivacion_Internet1.setBounds(130, 70, 100, 20);

        jLabel27.setText("Activacion de Internet");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(10, 70, 140, 14);
        jPanel1.add(jTFnum_telefono1);
        jTFnum_telefono1.setBounds(130, 40, 110, 20);
        jPanel1.add(jTFCodigo1);
        jTFCodigo1.setBounds(130, 10, 100, 20);

        jLabel28.setText("Activacion Correo");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(270, 40, 100, 14);

        jLabel29.setText("Bloqueado por robo");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(270, 10, 100, 14);

        jCBactivacion_correo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBactivacion_correo1);
        jCBactivacion_correo1.setBounds(390, 40, 100, 20);

        jLabel12.setText("Codigo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 10, 60, 14);

        jCBbloqueado_por_robo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBbloqueado_por_robo1);
        jCBbloqueado_por_robo1.setBounds(390, 10, 100, 20);

        jTabbedPane1.addTab("SimCard", jPanel1);

        jPanel6.setLayout(null);

        jLabel16.setText("Telefono Destino");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(10, 100, 100, 14);

        jTFSimdCardEnviarMensaje.setEditable(false);
        jTFSimdCardEnviarMensaje.setEnabled(false);
        jPanel6.add(jTFSimdCardEnviarMensaje);
        jTFSimdCardEnviarMensaje.setBounds(110, 10, 100, 20);

        jLabel35.setText("Cia. Internacional");
        jPanel6.add(jLabel35);
        jLabel35.setBounds(10, 70, 100, 14);

        jDCFechaEnviarMensaje.setDateFormatString("dd MMM yyyy");
        jPanel6.add(jDCFechaEnviarMensaje);
        jDCFechaEnviarMensaje.setBounds(110, 40, 160, 20);

        jLabel36.setText("Hora");
        jPanel6.add(jLabel36);
        jLabel36.setBounds(300, 40, 60, 14);

        jCBCompaniaInternacionalEnviarMensaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel6.add(jCBCompaniaInternacionalEnviarMensaje);
        jCBCompaniaInternacionalEnviarMensaje.setBounds(110, 70, 190, 20);

        jLabel17.setText("SimCard");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(10, 10, 60, 14);
        jPanel6.add(jTFTelDestinoEnviarMensaje);
        jTFTelDestinoEnviarMensaje.setBounds(110, 100, 130, 20);

        jLabel37.setText("Fecha");
        jPanel6.add(jLabel37);
        jLabel37.setBounds(10, 40, 60, 14);

        jBEnviarMensaje.setText("Enviar Mensaje");
        jBEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEnviarMensajeActionPerformed(evt);
            }
        });
        jPanel6.add(jBEnviarMensaje);
        jBEnviarMensaje.setBounds(240, 140, 120, 23);

        jTFHoraEnviarMensaje.setEditable(false);
        jTFHoraEnviarMensaje.setEnabled(false);
        jPanel6.add(jTFHoraEnviarMensaje);
        jTFHoraEnviarMensaje.setBounds(340, 40, 100, 20);

        jTabbedPaneMensajes.addTab("Enviar Mensaje", jPanel6);

        jPanel2.setLayout(null);

        jLabel13.setText("Telefono Origen");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 100, 100, 14);

        jTFSimdCardRecibirMensaje.setEditable(false);
        jTFSimdCardRecibirMensaje.setEnabled(false);
        jPanel2.add(jTFSimdCardRecibirMensaje);
        jTFSimdCardRecibirMensaje.setBounds(110, 10, 100, 20);

        jLabel30.setText("Cia. Internacional");
        jPanel2.add(jLabel30);
        jLabel30.setBounds(10, 70, 100, 14);

        jDCFechaRecibirMensaje.setDateFormatString("dd MMM yyyy");
        jPanel2.add(jDCFechaRecibirMensaje);
        jDCFechaRecibirMensaje.setBounds(110, 40, 160, 20);

        jLabel31.setText("Hora");
        jPanel2.add(jLabel31);
        jLabel31.setBounds(300, 40, 60, 14);

        jCBCompaniaInternacionalRecibirMensaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel2.add(jCBCompaniaInternacionalRecibirMensaje);
        jCBCompaniaInternacionalRecibirMensaje.setBounds(110, 70, 190, 20);

        jLabel14.setText("SimCard");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 10, 60, 14);
        jPanel2.add(jTFTelOrigenRecibirMensaje);
        jTFTelOrigenRecibirMensaje.setBounds(110, 100, 130, 20);

        jLabel32.setText("Fecha");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(10, 40, 60, 14);

        jButton1.setText("Recibir Mensaje");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(240, 140, 120, 23);

        jTFHoraRecibirMensaje.setEditable(false);
        jTFHoraRecibirMensaje.setEnabled(false);
        jPanel2.add(jTFHoraRecibirMensaje);
        jTFHoraRecibirMensaje.setBounds(340, 40, 100, 20);

        jTabbedPaneMensajes.addTab("Recibir Mensaje", jPanel2);

        jPanel4.setLayout(null);

        jLabel15.setText("SimCard");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 10, 60, 14);

        jTFSimdCardConsultarMsmRecibidos.setEditable(false);
        jTFSimdCardConsultarMsmRecibidos.setEnabled(false);
        jPanel4.add(jTFSimdCardConsultarMsmRecibidos);
        jTFSimdCardConsultarMsmRecibidos.setBounds(110, 10, 100, 20);

        jLabel33.setText("Fecha");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(10, 40, 60, 14);

        jDCFechaConsultarMsmRecibidos.setDateFormatString("dd MMM yyyy");
        jPanel4.add(jDCFechaConsultarMsmRecibidos);
        jDCFechaConsultarMsmRecibidos.setBounds(110, 40, 160, 20);

        jLabel34.setText("Cia. Internacional");
        jPanel4.add(jLabel34);
        jLabel34.setBounds(10, 70, 100, 14);

        jCBCompaniaInternacionalConsultarMsmRecibidos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel4.add(jCBCompaniaInternacionalConsultarMsmRecibidos);
        jCBCompaniaInternacionalConsultarMsmRecibidos.setBounds(110, 70, 190, 20);

        jTResultadosConsultarMsmRecibidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SimCard", "Fecha", "Hora", "Cia. Internacional", "Tel. Origen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTResultadosConsultarMsmRecibidos);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 490, 125);

        jBConsultarMensajes_Recibidos.setText("Consultar");
        jPanel4.add(jBConsultarMensajes_Recibidos);
        jBConsultarMensajes_Recibidos.setBounds(330, 30, 110, 23);

        jTabbedPaneMensajes.addTab("Consultar Mensajes Recibidos", jPanel4);

        jPanel5.setLayout(null);

        jLabel18.setText("SimCard");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(10, 10, 60, 14);

        jTFSimdCardConsultarMsmEnviados.setEditable(false);
        jTFSimdCardConsultarMsmEnviados.setEnabled(false);
        jPanel5.add(jTFSimdCardConsultarMsmEnviados);
        jTFSimdCardConsultarMsmEnviados.setBounds(110, 10, 100, 20);

        jLabel38.setText("Fecha");
        jPanel5.add(jLabel38);
        jLabel38.setBounds(10, 40, 60, 14);

        jDCFechaConsultarMsmEnviados.setDateFormatString("dd MMM yyyy");
        jPanel5.add(jDCFechaConsultarMsmEnviados);
        jDCFechaConsultarMsmEnviados.setBounds(110, 40, 160, 20);

        jLabel39.setText("Cia. Internacional");
        jPanel5.add(jLabel39);
        jLabel39.setBounds(10, 70, 100, 14);

        jCBCompaniaInternacionalConsultarMsmEnviados.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cargar Compania Internacional" }));
        jPanel5.add(jCBCompaniaInternacionalConsultarMsmEnviados);
        jCBCompaniaInternacionalConsultarMsmEnviados.setBounds(110, 70, 190, 20);

        jTResultadosMensajesEnviados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SimCard", "Fecha", "Hora", "Cia. Internacional", "Tel. Destino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTResultadosMensajesEnviados);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(10, 110, 490, 125);

        jBConsultarMensajes_Enviados.setText("Consultar");
        jPanel5.add(jBConsultarMensajes_Enviados);
        jBConsultarMensajes_Enviados.setBounds(330, 30, 110, 23);

        jTabbedPaneMensajes.addTab("Consultar Mensajes Enviados", jPanel5);

        jTabbedPane1.addTab("Mensaje", jTabbedPaneMensajes);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 10, 520, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked
        int selectedRow = jTResultados.getSelectedRow();
        jTFSimdCardRecibirMensaje.setText("" + jTResultados.getModel().getValueAt(selectedRow, 0));
        jTabbedPane1.setSelectedIndex(1);
        jDCFechaRecibirMensaje.setDate(new Date());

        // Agregar hora actual
        Calendar c = Calendar.getInstance();
        String hora = c.get(Calendar.HOUR_OF_DAY) + ":" + c.get(Calendar.MINUTE) + ":" + c.get(Calendar.SECOND);
        jTFHoraRecibirMensaje.setText(hora);
        //System.out.println(hora);



    }//GEN-LAST:event_jTResultadosMouseClicked

    private void jBConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultar1ActionPerformed
        // TODO add your handling code here:
        LinkedList consulta = new LinkedList();
        try {

            consulta = cs.consultar(
                    jTFCodigo1.getText(),
                    jTFnum_telefono1.getText(),
                    jCBActivacion_Internet1.getSelectedItem().toString(),
                    jCBbloqueado_por_robo1.getSelectedItem().toString(),
                    jCBactivacion_correo1.getSelectedItem().toString(),
                    jCBautorizacion_roaming1.getSelectedItem().toString());

            Object[][] s = new Object[consulta.size()][6];
            for (int i = 0; i < consulta.size(); i++) {
                Simcard sim = (Simcard) consulta.get(i);
                if (sim.getCodigo() != null) {
                    s[i][0] = sim.getCodigo();
                    s[i][1] = sim.getNum_telefono();
                    s[i][2] = sim.getActivacion_internet();
                    s[i][3] = sim.getBloqueado_por_robo();
                    s[i][4] = sim.getActivacion_correo();
                    s[i][5] = sim.getAutorizacion_roaming();
                } else {
                    s = null;
                }
            }
            TableModel myModel = new DefaultTableModel(s, new String[]{"Codigo", "Numero Tel", "Internet", "Bloqueado", "Correo", "Roaming"}) {

                boolean[] canEdit = new boolean[]{false, false, false, false, false, false
                };

                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit[columnIndex];
                }
            };
            ///remover filas
            jTResultados.setModel(myModel);
            jTResultados.setRowSorter(new TableRowSorter(myModel));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jBConsultar1ActionPerformed

    private void jBLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiar1ActionPerformed

    }//GEN-LAST:event_jBLimpiar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Calendar c = Calendar.getInstance();
        String hora = c.get(Calendar.HOUR_OF_DAY) + ":" + c.get(Calendar.MINUTE) + ":" + c.get(Calendar.SECOND);
        System.out.println(hora);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEnviarMensajeActionPerformed

    }//GEN-LAST:event_jBEnviarMensajeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar1;
    private javax.swing.JButton jBConsultarMensajes_Enviados;
    private javax.swing.JButton jBConsultarMensajes_Recibidos;
    private javax.swing.JButton jBEnviarMensaje;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBActivacion_Internet1;
    private javax.swing.JComboBox jCBCompaniaInternacionalConsultarMsmEnviados;
    private javax.swing.JComboBox jCBCompaniaInternacionalConsultarMsmRecibidos;
    private javax.swing.JComboBox jCBCompaniaInternacionalEnviarMensaje;
    private javax.swing.JComboBox jCBCompaniaInternacionalRecibirMensaje;
    private javax.swing.JComboBox jCBactivacion_correo1;
    private javax.swing.JComboBox jCBautorizacion_roaming1;
    private javax.swing.JComboBox jCBbloqueado_por_robo1;
    private com.toedter.calendar.JDateChooser jDCFechaConsultarMsmEnviados;
    private com.toedter.calendar.JDateChooser jDCFechaConsultarMsmRecibidos;
    private com.toedter.calendar.JDateChooser jDCFechaEnviarMensaje;
    private com.toedter.calendar.JDateChooser jDCFechaRecibirMensaje;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFCodigo1;
    private javax.swing.JTextField jTFHoraEnviarMensaje;
    private javax.swing.JTextField jTFHoraRecibirMensaje;
    private javax.swing.JTextField jTFSimdCardConsultarMsmEnviados;
    private javax.swing.JTextField jTFSimdCardConsultarMsmRecibidos;
    private javax.swing.JTextField jTFSimdCardEnviarMensaje;
    private javax.swing.JTextField jTFSimdCardRecibirMensaje;
    private javax.swing.JTextField jTFTelDestinoEnviarMensaje;
    private javax.swing.JTextField jTFTelOrigenRecibirMensaje;
    private javax.swing.JTextField jTFnum_telefono1;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTable jTResultadosConsultarMsmRecibidos;
    private javax.swing.JTable jTResultadosMensajesEnviados;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPaneMensajes;
    // End of variables declaration//GEN-END:variables
}
