/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author JUANPAULO
 */
public class JPSimCard extends javax.swing.JPanel {

    /**
     * Creates new form JPSimCard
     */
    public JPSimCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTFCodigo1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFnum_telefono1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jBLimpiar1 = new javax.swing.JButton();
        jBCrear1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCBactivacion_correo1 = new javax.swing.JComboBox();
        jCBActivacion_Internet1 = new javax.swing.JComboBox();
        jCBautorizacion_roaming1 = new javax.swing.JComboBox();
        jCBbloqueado_por_robo1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();
        jBConsultar2 = new javax.swing.JButton();
        jBLimpiar2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jCBautorizacion_roaming2 = new javax.swing.JComboBox();
        jCBActivacion_Internet2 = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jTFnum_telefono2 = new javax.swing.JTextField();
        jTFCodigo2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jCBactivacion_correo2 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jCBbloqueado_por_robo2 = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jBModificar3 = new javax.swing.JButton();
        jTFtarifa_msj_multimedia3 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTFCodigo3 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTcosto_min_adicional3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTtotal_minutos3 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTtarifa_msj_texto3 = new javax.swing.JTextField();
        jTFtarifa_otro_operador3 = new javax.swing.JTextField();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sim Card"));
        jPanel3.setLayout(null);

        jPanel4.setLayout(null);

        jLabel9.setText("Codigo");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 10, 60, 14);
        jPanel4.add(jTFCodigo1);
        jTFCodigo1.setBounds(130, 10, 100, 20);

        jLabel6.setText("Numero Tel");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 40, 70, 14);
        jPanel4.add(jTFnum_telefono1);
        jTFnum_telefono1.setBounds(130, 40, 110, 20);

        jLabel8.setText("Autorizacion Roaming");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 160, 110, 14);

        jBLimpiar1.setText("Limpiar");
        jPanel4.add(jBLimpiar1);
        jBLimpiar1.setBounds(50, 190, 72, 23);

        jBCrear1.setText("Crear");
        jPanel4.add(jBCrear1);
        jBCrear1.setBounds(160, 190, 70, 23);

        jLabel13.setText("Activacion de Internet");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 70, 140, 14);

        jLabel14.setText("Bloqueado por robo");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(10, 100, 100, 14);

        jLabel15.setText("Activacion Correo");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 130, 100, 14);

        jCBactivacion_correo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel4.add(jCBactivacion_correo1);
        jCBactivacion_correo1.setBounds(130, 130, 100, 20);

        jCBActivacion_Internet1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel4.add(jCBActivacion_Internet1);
        jCBActivacion_Internet1.setBounds(130, 70, 100, 20);

        jCBautorizacion_roaming1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel4.add(jCBautorizacion_roaming1);
        jCBautorizacion_roaming1.setBounds(130, 160, 100, 20);

        jCBbloqueado_por_robo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel4.add(jCBbloqueado_por_robo1);
        jCBbloqueado_por_robo1.setBounds(130, 100, 100, 20);

        jTabbedPane1.addTab("Crear", jPanel4);

        jPanel1.setLayout(null);

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Numero Tel", "Internet", "Bloqueado", "Correo", "Roaming"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTResultadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTResultados);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 490, 125);

        jBConsultar2.setText("Consultar");
        jPanel1.add(jBConsultar2);
        jBConsultar2.setBounds(260, 100, 100, 23);

        jBLimpiar2.setText("Limpiar");
        jPanel1.add(jBLimpiar2);
        jBLimpiar2.setBounds(390, 100, 100, 23);

        jLabel10.setText("Autorizacion Roaming");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(270, 70, 110, 14);

        jLabel11.setText("Numero Tel");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 40, 70, 14);

        jCBautorizacion_roaming2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBautorizacion_roaming2);
        jCBautorizacion_roaming2.setBounds(390, 70, 100, 20);

        jCBActivacion_Internet2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBActivacion_Internet2);
        jCBActivacion_Internet2.setBounds(130, 70, 100, 20);

        jLabel27.setText("Activacion de Internet");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(10, 70, 140, 14);
        jPanel1.add(jTFnum_telefono2);
        jTFnum_telefono2.setBounds(130, 40, 110, 20);
        jPanel1.add(jTFCodigo2);
        jTFCodigo2.setBounds(130, 10, 100, 20);

        jLabel28.setText("Activacion Correo");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(270, 40, 100, 14);

        jLabel29.setText("Bloqueado por robo");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(270, 10, 100, 14);

        jCBactivacion_correo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBactivacion_correo2);
        jCBactivacion_correo2.setBounds(390, 40, 100, 20);

        jLabel12.setText("Codigo");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 10, 60, 14);

        jCBbloqueado_por_robo2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "Si", "No" }));
        jPanel1.add(jCBbloqueado_por_robo2);
        jCBbloqueado_por_robo2.setBounds(390, 10, 100, 20);

        jTabbedPane1.addTab("Consultar", jPanel1);

        jPanel2.setLayout(null);

        jBModificar3.setText("Modificar");
        jPanel2.add(jBModificar3);
        jBModificar3.setBounds(120, 200, 90, 23);
        jPanel2.add(jTFtarifa_msj_multimedia3);
        jTFtarifa_msj_multimedia3.setBounds(120, 70, 110, 20);

        jLabel21.setText("Tarifa msj texto");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(10, 100, 100, 14);

        jTFCodigo3.setEditable(false);
        jTFCodigo3.setEnabled(false);
        jPanel2.add(jTFCodigo3);
        jTFCodigo3.setBounds(120, 10, 100, 20);

        jLabel22.setText("Total minutos");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(10, 130, 100, 14);

        jLabel23.setText("Codigo");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(10, 10, 60, 14);
        jPanel2.add(jTcosto_min_adicional3);
        jTcosto_min_adicional3.setBounds(120, 160, 110, 20);

        jLabel24.setText("Tarifa msj multimedia");
        jPanel2.add(jLabel24);
        jLabel24.setBounds(10, 70, 120, 14);

        jLabel25.setText("Tarifa otro op.");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(10, 40, 70, 14);
        jPanel2.add(jTtotal_minutos3);
        jTtotal_minutos3.setBounds(120, 130, 110, 20);

        jLabel26.setText("Costo min adicional");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(10, 160, 110, 14);

        jTtarifa_msj_texto3.setText(" ");
        jPanel2.add(jTtarifa_msj_texto3);
        jTtarifa_msj_texto3.setBounds(120, 100, 110, 20);
        jPanel2.add(jTFtarifa_otro_operador3);
        jTFtarifa_otro_operador3.setBounds(120, 40, 110, 20);

        jTabbedPane1.addTab("Editar", jPanel2);

        jPanel3.add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 20, 520, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTResultadosMouseClicked

    }//GEN-LAST:event_jTResultadosMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsultar2;
    private javax.swing.JButton jBCrear1;
    private javax.swing.JButton jBLimpiar1;
    private javax.swing.JButton jBLimpiar2;
    private javax.swing.JButton jBModificar3;
    private javax.swing.JComboBox jCBActivacion_Internet1;
    private javax.swing.JComboBox jCBActivacion_Internet2;
    private javax.swing.JComboBox jCBactivacion_correo1;
    private javax.swing.JComboBox jCBactivacion_correo2;
    private javax.swing.JComboBox jCBautorizacion_roaming1;
    private javax.swing.JComboBox jCBautorizacion_roaming2;
    private javax.swing.JComboBox jCBbloqueado_por_robo1;
    private javax.swing.JComboBox jCBbloqueado_por_robo2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCodigo1;
    private javax.swing.JTextField jTFCodigo2;
    private javax.swing.JTextField jTFCodigo3;
    private javax.swing.JTextField jTFnum_telefono1;
    private javax.swing.JTextField jTFnum_telefono2;
    private javax.swing.JTextField jTFtarifa_msj_multimedia3;
    private javax.swing.JTextField jTFtarifa_otro_operador3;
    private javax.swing.JTable jTResultados;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTcosto_min_adicional3;
    private javax.swing.JTextField jTtarifa_msj_texto3;
    private javax.swing.JTextField jTtotal_minutos3;
    // End of variables declaration//GEN-END:variables
}
